//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.data;

/**
* Class that represent the table countries
* @author Administrator
*/
public class countriesData extends mainData {
	 protected String description;
	 protected int cod_pais;

	 public void setdescription(String val) { description = val; } 
	 public void setcod_pais(int val) { cod_pais = val; } 

	 public String getdescription() { return description;}
	 public int getcod_pais() { return cod_pais;}

	 public String toString() {
		 return" description:" + description + " cod_pais:" + cod_pais; 
	 }
}