//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.data;

/**
* Class that represent the table logs
* @author Administrator
*/
public class logsData extends mainData {
	 protected java.sql.Timestamp last_visite;
	 protected String login;
	 protected String password;
	 protected String connected;
	 protected String session;
	 protected int compt;
	 protected String ip;
	 protected int id;

	 public void setlast_visite(java.sql.Timestamp val) { last_visite = val; } 
	 public void setlogin(String val) { login = val; } 
	 public void setpassword(String val) { password = val; } 
	 public void setconnected(String val) { connected = val; } 
	 public void setsession(String val) { session = val; } 
	 public void setcompt(int val) { compt = val; } 
	 public void setip(String val) { ip = val; } 
	 public void setid(int val) { id = val; } 

	 public java.sql.Timestamp getlast_visite() { return last_visite;}
	 public String getlogin() { return login;}
	 public String getpassword() { return password;}
	 public String getconnected() { return connected;}
	 public String getsession() { return session;}
	 public int getcompt() { return compt;}
	 public String getip() { return ip;}
	 public int getid() { return id;}

	 public String toString() {
		 return" last_visite:" + last_visite + " login:" + login + " password:" + password + " connected:" + connected + " session:" + session + " compt:" + compt + " ip:" + ip + " id:" + id; 
	 }
}