//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.data;

/**
* Class that represent the table organizations
* @author Administrator
*/
public class organizationsData extends mainData {
	 protected String url;
	 protected String address2;
	 protected String name;
	 protected int id;
	 protected String address1;
	 protected int cod_pais;
	 protected String zip_code;
	 protected String email_collect;
	 protected java.sql.Timestamp created;
	 protected String city;
	 //protected char[] comments;
          protected String comments;
	 protected String phone;
	 protected String email;
private int id_account;
private int serversSupport;

	 public void seturl(String val) { url = val; } 
	 public void setaddress2(String val) { address2 = val; } 
	 public void setname(String val) { name = val; } 
	 public void setid(int val) { id = val; } 
	 public void setaddress1(String val) { address1 = val; } 
	 public void setcod_pais(int val) { cod_pais = val; } 
	 public void setzip_code(String val) { zip_code = val; } 
	 public void setemail_collect(String val) { email_collect = val; } 
	 public void setcreated(java.sql.Timestamp val) { created = val; } 
	 public void setcity(String val) { city = val; } 
	/*public void setcomments(char[] val) { comments = val; } 
         public void setcomments(String val) { comments = val.toCharArray(); }*/
          public void setcomments(String val) { comments = val; }
	 public void setphone(String val) { phone = val; } 
	 public void setemail(String val) { email = val; } 

	 public String geturl() { return url;}
	 public String getaddress2() { return address2;}
	 public String getname() { return name;}
	 public int getid() { return id;}
	 public String getaddress1() { return address1;}
	 public int getcod_pais() { return cod_pais;}
	 public String getzip_code() { return zip_code;}
	 public String getemail_collect() { return email_collect;}
	 public java.sql.Timestamp getcreated() { return created;}
	 public String getcity() { return city;}
	 //public char[] getcomments() { return comments;}
         public String getcomments() { return comments;}
	 public String getphone() { return phone;}
	 public String getemail() { return email;}

	 public String toString() {
		 return" url:" + url + " address2:" + address2 + " name:" + name + " id:" + 
                 id + " address1:" + address1 + " cod_pais:" + cod_pais + " zip_code:" + zip_code + 
                 " email_collect:" + email_collect + " created:" + created + " city:" + city 
                         //+ " comments:" 
                         //+  (comments==null?"":new String(comments)) 
                         + " phone:" + phone + " email:" + email; 
	 }

    public int getId_account() {
        return id_account;
    }

    public void setId_account(int id_account) {
        this.id_account = id_account;
    }

    public int getServersSupport() {
        return serversSupport;
    }

    public void setServersSupport(int serversSupport) {
        this.serversSupport = serversSupport;
    }
    
}