//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.data;
import java.util.Date;
/**
* Class that represent the table reports
* @author Administrator
*/
public class reportsData extends mainData {
	 protected String name;
         protected java.sql.Timestamp start_date_start;
	 protected java.sql.Timestamp end_date_start;
         protected java.sql.Timestamp start_date_due;
	 protected java.sql.Timestamp end_date_due;
         protected java.sql.Timestamp start_date_end;
	 protected java.sql.Timestamp end_date_end;         
         
         protected String ind_range_start_date;
         protected String ind_range_due_date;
         protected String ind_range_end_date;

	 protected int id;
	 protected int owner;
	 protected java.sql.Timestamp created;
	 protected String projects;
	 protected String members;
         private String QA_assigned;
         private String RF_assigned;
	 protected String status;	 
	 protected String priorities;
         protected String spreadfix;
         protected String typetasks;
         private String chargeable;
private int id_account;
	 public void setname(String val) { name = val; } 
	 public void setid(int val) { id = val; } 
	 public void setowner(int val) { owner = val; } 
	 public void setcreated(java.sql.Timestamp val) { created = val; } 
	 public void setprojects(String val) { projects = val; } 
	 public void setmembers(String val) { members = val; } 
	 public void setstatus(String val) { status = val; } 
	 public void setstart_date_start(java.sql.Timestamp val) { start_date_start = val; } 
	 public void setend_date_start(java.sql.Timestamp val) { end_date_start = val; }          
	 public void setstart_date_due(java.sql.Timestamp val) { start_date_due = val; } 
	 public void setend_date_due(java.sql.Timestamp val) { end_date_due = val; }        
         
	 public void setstart_date_end(java.sql.Timestamp val) { start_date_end = val; } 
	 public void setend_date_end(java.sql.Timestamp val) { end_date_end = val; }      
         
	 public void setpriorities(String val) { priorities = val; } 
         public void setind_range_start_date(String val) { ind_range_start_date = val; } 
         public void setind_range_due_date(String val) { ind_range_due_date = val; } 
         public void setind_range_end_date(String val) { ind_range_end_date = val; } 
         public void setspreadfix(String val) { spreadfix =  val; }
         public void settypetasks(String val) { typetasks =  val; }

         
	 public String getname() { return name;}
	 public int getid() { return id;}
	 public int getowner() { return owner;}
	 public java.sql.Timestamp getcreated() { return created;}
	 public String getprojects() { return projects;}
	 public String getmembers() { return members;}
	 public String getstatus() { return status;}
	 public java.sql.Timestamp getend_date_start() { return end_date_start;}         
	 public java.sql.Timestamp getstart_date_start() { return start_date_start;}
	 public java.sql.Timestamp getend_date_due() { return end_date_due;}         
	 public java.sql.Timestamp getstart_date_due() { return start_date_due;}     
         
	 public java.sql.Timestamp getend_date_end() { return end_date_end;}         
	 public java.sql.Timestamp getstart_date_end() { return start_date_end;}              
	 
         public String getpriorities() { return priorities;}
         public String getind_range_start_date() { return ind_range_start_date; } 
         public String getind_range_due_date() { return ind_range_due_date; }   
         public String getind_range_end_date() { return ind_range_end_date; }  
         public String getspreadfix() { return spreadfix; }
         public String gettypetasks() { return typetasks; }
         
         
         public String getFormatedCreateDate() {
            java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("dd-MMM-yyyy HH:mm");
             
             try {
                return format.format(new Date(created.getTime()));
             } catch (Exception e) {          
                 return "";
             }
         }

	 public String toString() {
		 return" name:" + name + " end_date:" + end_date_start + " id:" + id + " owner:" + owner + " created:" + created + " projects:" + projects + " members:" + members + " status:" + status + " start_date:" + start_date_start + " priorities:" + priorities; 
	 }

    public int getId_account() {
        return id_account;
    }

    public void setId_account(int id_account) {
        this.id_account = id_account;
    }

    /**
     * @return the chargeable
     */
    public String getChargeable() {
        return chargeable;
    }

    /**
     * @param chargeable the chargeable to set
     */
    public void setChargeable(String chargeable) {
        this.chargeable = chargeable;
    }

    public String getQA_assigned() {
        return QA_assigned;
    }

    public void setQA_assigned(String QA_assigned) {
        this.QA_assigned = QA_assigned;
    }

    public String getRF_assigned() {
        return RF_assigned;
    }

    public void setRF_assigned(String RF_assigned) {
        this.RF_assigned = RF_assigned;
    }
    
    
}