//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.data;

/**
* Class that represent the table teams
* @author Administrator
*/
public class teamsData extends mainData {
	 protected String authorized;
	 protected int members;
	 protected int projects;
	 protected String published;
	 protected int id;
         protected membersData parentMember;
         private projectsData parentProject;
private int id_account;
         public teamsData() {
             
         }
         
         public teamsData(teamsData val) {
             this.id = 0;
             this.members = val.getmembers();
             this.projects = val.getprojects();
             this.authorized = val.getauthorized();
             this.published=val.getpublished();
         }
         
	 public void setauthorized(String val) { authorized = val; } 
	 public void setmembers(int val) { members = val; } 
	 public void setprojects(int val) { projects = val; } 
	 public void setpublished(String val) { published = val; } 
	 public void setid(int val) { id = val; } 
         public void setparentMember(membersData val) { parentMember = val; }
         
	 public String getauthorized() { return authorized;}
	 public int getmembers() { return members;}
	 public int getprojects() { return projects;}
	 public String getpublished() { return published;}
	 public int getid() { return id;}
         public membersData getparentMember() { return parentMember; }

	 public String toString() {
		 return" authorized:" + authorized + " members:" + members + " projects:" + projects + " published:" + published + " id:" + id; 
	 }

    public int getId_account() {
        return id_account;
    }

    public void setId_account(int id_account) {
        this.id_account = id_account;
    }

    /**
     * @return the parentProject
     */
    public projectsData getParentProject() {
        return parentProject;
    }

    /**
     * @param parentProject the parentProject to set
     */
    public void setParentProject(projectsData parentProject) {
        this.parentProject = parentProject;
    }
}