//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.*;
import org.apache.struts.validator.ValidatorActionForm;

/**
* Class that represent the form for the table countries
* @author Administrator
*/
public class countriesForm  extends ValidatorActionForm {

	 private String operation;
	 private String sortColumn;
	 private String sortOrder;
	 private String description;
	 private int cod_pais;

	 public void setdescription(String val) { description = val; } 
	 public void setcod_pais(int val) { cod_pais = val; } 
	 public void setOperation(String val) { operation =  val; }
	 public void setsortColumn(String val) { sortColumn =  val; }
	 public void setsortOrder(String val) { sortOrder =  val; }

	 public String getdescription() { return description;}
	 public int getcod_pais() { return cod_pais;}
	 public String getOperation() { return operation; }
	 public String getsortColumn() { return sortColumn; }
	 public String getsortOrder() { return sortOrder; }

	 /**
	 * Reset all properties to their default values.
	 *
	 * @param mapping The mapping used to select this instance
	 * @param request The servlet request we are processing
	 */
	 public void reset(ActionMapping mapping, HttpServletRequest request) {
		description = "";
		cod_pais = 0;
		sortColumn = "";
		sortOrder = "DESC";
	}

	 public String toString() {
		 return " description:" + description + " cod_pais:" + cod_pais; 
	 }
}