//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.*;
import org.apache.struts.validator.ValidatorActionForm;

/**
* Class that represent the form for the table members
* @author Administrator
*/
public class membersForm  extends ValidatorActionForm {

	 private String operation;
	 private String sortColumn;
	 private String sortOrder;
	 private String personal_title;
	 private String password;
	 private String last_page;
	 private String mobile;
	 private String profile;
	 private String reports;
	 private int logout_time;
	 private String phone_work;
	 private java.sql.Timestamp created;
	 //private char[] comments;
         private String comments;
	 private String email_work;
	 private String phone_home;
	 private String quotation;
	 private String login;
	 private String email_home;
	 private int id;
	 private String fax;
	 private String title;
	 private int organization;
	 private String name;
         private String fromPage;
         private String template;
         private String ind_check_schedules;    
         private String ind_end_tasks;
         private String time_zone;
         private java.math.BigDecimal cost;
         protected String ind_client_manager;
              private int id_account;
                private  java.sql.Timestamp expired_date;
         private  java.sql.Timestamp renew_date;
         private  java.math.BigDecimal sale_cost;
         private String expiredDate;
         
            //Se agrego el nuevo campo para el permiso de ejecucion del reporte de
         //actividades
                private String ind_exec_report;
        // nuevos campos para permisos sobre el control de aplicaciones
                private int permission_delete_operation_number;
                private int permission_view_app_control;
                private int permission_app_control;
                private int permission_version_control;
                private int permission_report_applications;
         
	 public void setpersonal_title(String val) { personal_title = val; } 
	 public void setpassword(String val) { password = val; } 
	 public void setlast_page(String val) { last_page = val; } 
	 public void setmobile(String val) { mobile = val; } 
	 public void setprofile(String val) { profile = val; } 
	 public void setreports(String val) { reports = val; } 
	 public void setlogout_time(int val) { logout_time = val; } 
	 public void setphone_work(String val) { phone_work = val; } 
	 public void setcreated(java.sql.Timestamp val) { created = val; } 	 
         /*public void setcomments(String val) {
             if (val!=null) 
                comments = val.toCharArray(); 
         } 
         public void setcomments(char[] val) { comments = val; } */
         public void setcomments(String val) { comments = val; } 
	 public void setemail_work(String val) { email_work = val; } 
	 public void setphone_home(String val) { phone_home = val; } 
	 public void setquotation(String val) { quotation = val; } 
	 public void setlogin(String val) { login = val; } 
	 public void setemail_home(String val) { email_home = val; } 
	 public void setid(int val) { id = val; } 
	 public void setfax(String val) { fax = val; } 
	 public void settitle(String val) { title = val; } 
	 public void setorganization(int val) { organization = val; } 
	 public void setname(String val) { name = val; } 
	 public void setOperation(String val) { operation =  val; }
	 public void setsortColumn(String val) { sortColumn =  val; }
	 public void setsortOrder(String val) { sortOrder =  val; }
         public void setfromPage(String val) { fromPage = val; }
         public void setTemplate(String val) { template = val; }
         public void setCost(java.math.BigDecimal val) { cost = val; }
         public void setind_check_schedules(String val) {ind_check_schedules = val; }
         public void setind_end_tasks(String val) {ind_end_tasks = val; } 
         public void setind_client_manager(String val) {ind_client_manager = val; }  

	 public String getpersonal_title() { return personal_title;}
	 public String getpassword() { return password;}
	 public String getlast_page() { return last_page;}
	 public String getmobile() { return mobile;}
	 public String getprofile() { return profile;}
	 public String getreports() { return reports;}
	 public int getlogout_time() { return logout_time;}
	 public String getphone_work() { return phone_work;}
	 public java.sql.Timestamp getcreated() { return created;}
	 public String getcomments() { return (comments!=null? new String(comments):"");}
	 public String getemail_work() { return email_work;}
	 public String getphone_home() { return phone_home;}
	 public String getquotation() { return quotation;}
	 public String getlogin() { return login;}
	 public String getemail_home() { return email_home;}
	 public int getid() { return id;}
	 public String getfax() { return fax;}
	 public String gettitle() { return title;}
	 public int getorganization() { return organization;}
	 public String getname() { return name;}
	 public String getOperation() { return operation; }
	 public String getsortColumn() { return sortColumn; }
	 public String getsortOrder() { return sortOrder; }
         public String getfromPage() { return fromPage; }
         public String getTemplate() { return template; }
         public String getind_check_schedules() { return ind_check_schedules; }
         public java.math.BigDecimal getCost() { return cost; }
         public String getind_end_tasks() { return ind_end_tasks; }
         public String getind_client_manager() { return ind_client_manager; }
        
	 /**
	 * Reset all properties to their default values.
	 *
	 * @param mapping The mapping used to select this instance
	 * @param request The servlet request we are processing
	 */
	 public void reset(ActionMapping mapping, HttpServletRequest request) {
		personal_title = " ";
		password = "";
		last_page = " ";
		mobile = " ";
		profile = "1";
		reports = "0";
		logout_time = 0;
		phone_work = "";
		created = null;
//		comments = " ";
		email_work = "";
		phone_home = "";
		quotation = "0";
		login = "";
		email_home = "";
		id = 0;
		fax = "";
		title = "";
		organization = 0;
		name = "";
		sortColumn = "";
		sortOrder = "DESC";
                fromPage = " ";
                template = "default";
                ind_check_schedules = "0";
                ind_check_schedules = "N";
                cost = new java.math.BigDecimal(0);
                id_account=0;
                expired_date=null;
                renew_date=null;
                sale_cost=new java.math.BigDecimal(0);
	}

	 public String toString() {
		 return " personal_title:" + personal_title + " password:" + password + " last_page:" + last_page + " mobile:" + mobile + " profile:" + profile + " reports:" + reports + " logout_time:" + logout_time + " phone_work:" + phone_work + " created:" + created + " comments:" + comments + " email_work:" + email_work + " phone_home:" + phone_home + " quotation:" + quotation + " login:" + login + " email_home:" + email_home + " id:" + id + " fax:" + fax + " title:" + title + " organization:" + organization + " name:" + name; 
	 }

    public String getTime_zone() {
        return time_zone;
    }

    public void setTime_zone(String time_zone) {
        this.time_zone = time_zone;
    }

    public int getId_account() {
        return id_account;
    }

    public void setId_account(int id_account) {
        this.id_account = id_account;
    }

    public java.sql.Timestamp getExpired_date() {
        return expired_date;
    }

    public void setExpired_date(java.sql.Timestamp expired_date) {
        this.expired_date = expired_date;
    }

    public java.sql.Timestamp getRenew_date() {
        return renew_date;
    }

    public void setRenew_date(java.sql.Timestamp renew_date) {
        this.renew_date = renew_date;
    }

    public java.math.BigDecimal getSale_cost() {
        return sale_cost;
    }

    public void setSale_cost(java.math.BigDecimal sale_cost) {
        this.sale_cost = sale_cost;
    }

    public String getExpiredDate() {
        return expiredDate;
    }

    public void setExpiredDate(String expiredDate) {
        this.expiredDate = expiredDate;
    }

    public String getInd_exec_report() {
        return ind_exec_report;
    }

    public void setInd_exec_report(String ind_exec_report) {
        this.ind_exec_report = ind_exec_report;
    }

    public int getPermission_delete_operation_number() {
        return permission_delete_operation_number;
    }

    public void setPermission_delete_operation_number(int permission_delete_operation_number) {
        this.permission_delete_operation_number = permission_delete_operation_number;
    }

    public int getPermission_view_app_control() {
        return permission_view_app_control;
    }

    public void setPermission_view_app_control(int permission_view_app_control) {
        this.permission_view_app_control = permission_view_app_control;
    }

    public int getPermission_app_control() {
        return permission_app_control;
    }

    public void setPermission_app_control(int permission_app_control) {
        this.permission_app_control = permission_app_control;
    }

    public int getPermission_version_control() {
        return permission_version_control;
    }

    public void setPermission_version_control(int permission_version_control) {
        this.permission_version_control = permission_version_control;
    }

    public int getPermission_report_applications() {
        return permission_report_applications;
    }

    public void setPermission_report_applications(int permission_report_applications) {
        this.permission_report_applications = permission_report_applications;
    }

   
    
    

}