//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.*;
import org.apache.struts.validator.ValidatorActionForm;

/**
* Class that represent the form for the table organizations
* @author Administrator
*/
public class organizationsForm  extends ValidatorActionForm {
 /** Creates a new instance of organizationsForm */
    public organizationsForm() {
    }
	 private String operation;
	 private String url;
	 private String address2;
	 private String name;
	 private int id;
	 private String address1;
	 private int cod_pais;
	 private String zip_code;
	 private String email_collect;
	 private java.sql.Timestamp created;
	 private String city;
	// private char[] comments;
          private String comments;
	 private String phone;
	 private String email;
         private String sortOrderProjects;
         private String sortColumnProjects;
         private String sortOrderMembers;
         private String sortColumnMembers;         
         private String source;
         
         private String sortColumn;
         private String sortOrder;
         
         private int pageProjects;
         private int pageMembers;
               private int typeProject;
               
	 public void seturl(String val) { url = val; } 
	 public void setaddress2(String val) { address2 = val; } 
	 public void setname(String val) { name = val; } 
	 public void setid(int val) { id = val; } 
	 public void setaddress1(String val) { address1 = val; } 
	 public void setcod_pais(int val) { cod_pais = val; } 
	 public void setzip_code(String val) { zip_code = val; } 
	 public void setemail_collect(String val) { email_collect = val; } 
	 public void setcreated(java.sql.Timestamp val) { created = val; } 
	 public void setcity(String val) { city = val; } 
	 /*public void setcomments(char[] val) { comments = val; } 
         public void setcomments(String val) { 
             if (val !=null) 
                 comments = val.toCharArray(); 
         } */
         public void setcomments(String val) { comments = val; } 
	 public void setphone(String val) { phone = val; } 
	 public void setemail(String val) { email = val; } 
         public void setoperation(String val) { operation = val; }
         public void setsortOrder(String val) { sortOrder = val; }
         public void setsortColumn(String val) { sortColumn = val; }

	 public String geturl() { return url;}
	 public String getaddress2() { return address2;}
	 public String getname() { return name;}
	 public int getid() { return id;}
	 public String getaddress1() { return address1;}
	 public int getcod_pais() { return cod_pais;}
	 public String getzip_code() { return zip_code;}
	 public String getemail_collect() { return email_collect;}
	 public java.sql.Timestamp getcreated() { return created;}
	 public String getcity() { return city;}
	 public String getcomments() {
             if (comments != null)
                return new String(comments);
             else
                 return "";
         }
	 public String getphone() { return phone;}
	 public String getemail() { return email;}
	 public String getOperation() { return operation; }
         public String getsortOrder() { return sortOrder; }
         public String getsortColumn() { return sortColumn; }

         public String getsortColumnProjects() { return sortColumnProjects; }
         public void setsortColumnProjects(String val) { sortColumnProjects = val; }
         public String getsortOrderProjects() { return sortOrderProjects; }
         public void setsortOrderProjects(String val) { sortOrderProjects = val; }         

         public String getsortColumnMembers() { return sortColumnMembers; }
         public void setsortColumnMembers(String val) { sortColumnMembers = val; }
         public String getsortOrderMembers() { return sortOrderMembers; }
         public void setsortOrderMembers(String val) { sortOrderMembers = val; }         
         
         
         public void setsource(String val) { source = val;}
         public String getsource() { return source; }

         public void setpageProjects(int val) { pageProjects = val; }
         public int getpageProjects() { return pageProjects; }
         
         public void setpageMembers(int val) { pageMembers = val; }
         public int getpageMembers() { return pageMembers; }         
         

         /**
	 * Reset all properties to their default values.
	 *
	 * @param mapping The mapping used to select this instance
	 * @param request The servlet request we are processing
	 */
	 public void reset(ActionMapping mapping, HttpServletRequest request) {
		url = "";
		address2 = "";
		name = "";
		id = 0;
		address1 = "";
		cod_pais = 0;
		zip_code = "";
		email_collect = "";
		created = null;
		city = "";
		phone = "";
		email = "";
                sortOrder = "DESC";
                sortColumn = "";
                source = ""; 
                sortColumnProjects = "status,id";
                sortOrderProjects = "ASC";
                sortColumnMembers = "name";
                sortOrderMembers = "DESC";
                pageMembers = 1;
                pageProjects = 1;
                typeProject = 2;
	}

	 public String toString() {
		 return " url:" + url + " address2:" + address2 + " name:" + name + " id:" + id + " address1:" + address1 + " cod_pais:" + cod_pais + " zip_code:" + zip_code + " email_collect:" + email_collect + " created:" + created + " city:" + city + " comments:" + comments + " phone:" + phone + " email:" + email; 
	 }

    public int getTypeProject() {
        return typeProject;
    }

    public void setTypeProject(int typeProject) {
        this.typeProject = typeProject;
    }
}