//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.*;
import org.apache.struts.validator.ValidatorActionForm;
import java.util.*;
import com.unify.webcenter.tools.*;
/**
* Class that represent the form for the table schedules
* @author Administrator
*/
public class schedulesForm  extends ValidatorActionForm {

	 protected int hourid;
	 protected int taskid;
	 protected int userid;
         protected String date;
         protected String hour_name;	 
         private String hour_end;
	 //protected char[] comments;	 
         protected String comments;	 
         protected java.sql.Timestamp last_update;
         private String operation;
	 private String sortColumn;
	 private String sortOrder;
         private String year;
         private String month;
         private String day;
         private int[] id;
         private int[] task;
         private String[] comment;
         private long   theDate;
         private String searchProject;
         private String searchCode;
         private String searchTask;
         
         
	 public void sethourid(int val) { hourid = val; }
         public void setTheDate(long val) { theDate = val; }
	 public void settaskid(int val) { taskid = val; } 
	 public void setuserid(int val) { userid = val; } 
         public void setdate(String val) { date = val; } 
         public void sethour_name(String val) { hour_name = val; } 	 
         /*public void setcomments(String val) { comments =val.toCharArray(); }
	 public void setcomments(char[] val) { 
             if (val == null || val.length == 0)
                 val = (new String(" ")).toCharArray();
             comments = val; 
         } */	 
         public void setcomments(String val) { comments =val; }
         public void setlast_update(java.sql.Timestamp val) { last_update = val; } 
	 public void setOperation(String val) { operation =  val; }
	 public void setsortColumn(String val) { sortColumn =  val; }
	 public void setsortOrder(String val) { sortOrder =  val; }        
         public void setYear(String val) { year =  val; }
         public void setMonth(String val) { month =  val; }
         public void setDay(String val) { day =  val; }
         public void setid(int[] val) { id =  val; }
         public void settask(int[] val) { task =  val; }
         public void setcomment(String[] val) { comment =  val; }

         
	 public int gethourid() { return hourid;}
         public long getTheDate() { return theDate; }
	 public int gettaskid() { return taskid;}
	 public int getuserid() { return userid;}
         public String getdate() { return date;}
         public String gethour_name() { return hour_name;}         	 
	 public String getcomments() { 
             if (comments != null)
                return new String(comments);
             else
                 return "";
         }
         public java.sql.Timestamp getlast_update() { return last_update;}
	 public String getOperation() { return operation; }
	 public String getsortColumn() { return sortColumn; }
	 public String getsortOrder() { return sortOrder; }
	 public String getYear() { return year;}
         public String getMonth() { return month;}
         public String getDay() { return day;}
         public int[] getid() { return id;}
         public int[] gettask() { return task;}
         public String[] getcomment() { return comment;}
         
	 /**
	 * Reset all properties to their default values.
	 *
	 * @param mapping The mapping used to select this instance
	 * @param request The servlet request we are processing
	 */
	 public void reset(ActionMapping mapping, HttpServletRequest request) {
		last_update = null;
		hour_name = "";
		taskid = 0;
		userid = 0;               
                //comments = (new String(" ")).toCharArray();
                comments = (new String(" "));
		hourid = 0;
		sortColumn = "date";
                Calendar calendar = Calendar.getInstance();
                year = "" + calendar.get(calendar.YEAR);
                month = "" + (calendar.get(calendar.MONTH)+1);
                day = "" + calendar.get(calendar.DAY_OF_MONTH);
                String month2 = month;
                String day2 = day;
                if (month.length() == 1) month2 = "0"+month;
                if (day.length() == 1) day2 = "0"+day;
                date = year+"-"+month2+"-"+day2;
                operation = "goTo";
                theDate = Calendar.getInstance().getTimeInMillis();
                setSearchProject("%");
                searchCode="%";
                searchTask="%";

	}

	 public String toString() {
		 return " last_update:" + last_update + " hourid:" + hourid + " taskid:" + taskid + " userid:" + userid + " date:" + date + " comments:" + comments + " hour_name:" + hour_name + "year" + year; 
	 }

  
    public String getSearchCode() {
        return searchCode;
    }

    public void setSearchCode(String searchCode) {
        this.searchCode = searchCode;
    }

    public String getSearchTask() {
        return searchTask;
    }

    public void setSearchTask(String searchTask) {
        this.searchTask = searchTask;
    }

    public String getSearchProject() {
        return searchProject;
    }

    public void setSearchProject(String searchProject) {
        this.searchProject = searchProject;
    }

    public String getHour_end() {
        return hour_end;
    }

    public void setHour_end(String hour_end) {
        this.hour_end = hour_end;
    }
}