//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.form;

import com.unify.webcenter.data.versionAppData;
import java.math.BigDecimal;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.*;
import org.apache.struts.validator.ValidatorActionForm;

/**
* Class that represent the form for the table tasks
* @author Administrator
*/
public class tasksForm  extends ValidatorActionForm {

	 private String operation;
	 private String sortColumn;
	 private String sortOrder;
         private String source;
         private String fromPage;  // Indica el lugar de origen de la invocacion a una accion de un task
         
         // Used in the view of a tasks for sorting purposes
         private String sortOrderFiles;
         private String sortColumnFiles;
         private String sortOrderAssignments;
         private String sortColumnAssignments;
         private String predecessorName;
         
         private int pageFiles;
         private int pageAssignments;
         
         private int owner;
	 private int project;
	 private java.sql.Timestamp start_date; 
	 private java.sql.Timestamp reply_quotation_date;
	 private int assigned_to;
	 private java.sql.Timestamp created;
	 private java.sql.Timestamp modified;
	 private String comments;
	 private java.math.BigDecimal estimated_time;
         	 private java.math.BigDecimal estimated_time_min;
	 private int completion;
	 private int  tolerance;
	 private String collect;
	 private int id;
	 private int topic;
	 private int status;
         private int message;
	 private java.math.BigDecimal fare;
	 //private char[] description;
         private String description;
	 private java.sql.Timestamp due_date;
         private java.sql.Timestamp real_due_date;
	 private int reply_quotation_member;
	 private java.math.BigDecimal actual_time;
	 private int priority;
	 private java.sql.Timestamp assigned;
	 private String published;
	 private java.sql.Timestamp send_quotation_date;
	 private String name;
         protected int predecessor;
         protected String predecessor_required;   
         private int topic2task;
         private String severity;
         protected int type_task;
         protected String spread_fix;
         private int finalizado;
         
         private int check_monto_fijo;
         private java.math.BigDecimal monto_manual;
         
        private int emailNotifyTQA;
        private int emailNotifyFQA;
        
        private int version_control;
        private int operation_number;
        private int verapp;
        private versionAppData parentVerApp;
    
         public void setcheck_monto_fijo(int val) { check_monto_fijo = val ;}
         public void setmonto_manual(java.math.BigDecimal val) { monto_manual = val; }
         
         public int getcheck_monto_fijo() { return check_monto_fijo ;}
         public java.math.BigDecimal getmonto_manual() { return monto_manual; }         
         
	 public void setowner(int val) { owner = val; } 
	 public void setproject(int val) { project = val; } 
	 public void setstart_date(java.sql.Timestamp val) { start_date = val; } 
	 public void setreply_quotation_date(java.sql.Timestamp val) { reply_quotation_date = val; } 
	 public void setassigned_to(int val) { assigned_to = val; } 
	 public void setcreated(java.sql.Timestamp val) { created = val; } 
	 public void setmodified(java.sql.Timestamp val) { modified = val; } 
	 public void setcomments(String val) { comments = val; } 
	 public void setestimated_time(java.math.BigDecimal val) { estimated_time = val; } 
	 public void setcompletion(int val) { completion = val; } 
	 public void settolerance(int val) { tolerance = val; } 
	 public void setcollect(String val) { collect = val; } 
	 public void setid(int val) { id = val; } 
	 public void settopic(int val) { topic = val; } 
	 public void setstatus(int val) { status = val; } 
	 public void setfare(java.math.BigDecimal val) { fare = val; } 
	 //public void setdescription(char[] val) { description = val; } 
         public void setdescription(String val) { description = val; } 
         public void setspread_fix(String val) { spread_fix = val; }
         
         public void setpredecessorName(String val) {
             predecessorName = val;
         }
        /* public void setdescription(String val) { 
             if (val != null)
                description = val.toCharArray(); 
         }*/
        public void setdue_date(java.sql.Timestamp val) { due_date = val; } 
         public void setreal_due_date(java.sql.Timestamp val) { real_due_date = val; } 
	 public void setreply_quotation_member(int val) { reply_quotation_member = val; } 
	 public void setactual_time(java.math.BigDecimal val) { actual_time = val; } 
	 public void setpriority(int val) { priority = val; } 
	 public void setassigned(java.sql.Timestamp val) { assigned = val; } 
	 public void setpublished(String val) { published = val; } 
	 public void setsend_quotation_date(java.sql.Timestamp val) { send_quotation_date = val; } 
	 public void setname(String val) { name = val; } 
         public void setmessage(int val) { message = val; } 
	 public void setOperation(String val) { operation =  val; }
	 public void setsortColumn(String val) { sortColumn =  val; }
	 public void setsortOrder(String val) { sortOrder =  val; }
         public void setsource(String val) { source =  val; }
	 public void setsortColumnFiles(String val) { sortColumnFiles =  val; }
	 public void setsortOrderFiles(String val) { sortOrderFiles =  val; }
	 public void setsortColumnAssignments(String val) { sortColumnAssignments =  val; }
	 public void setsortOrderAssignments(String val) { sortOrderAssignments =  val; }
         public void setfromPage(String val) { fromPage = val; }
         public void setpredecessor(int val) { predecessor = val; }
         public void setpredecessor_required(String val) { predecessor_required = val; }
         public void settopic2task(int val) { topic2task = val; }
         public void setseverity(String val) { severity = val; }
         public void settype_task(int val) { type_task = val; }
         
         public String getfromPage() { return fromPage; }
	 public int getowner() { return owner;}
	 public int getproject() { return project;}
	 public java.sql.Timestamp getstart_date() { return start_date;}
	 public java.sql.Timestamp getreply_quotation_date() { return reply_quotation_date;}
	 public int getassigned_to() { return assigned_to;}
	 public java.sql.Timestamp getcreated() { return created;}
	 public java.sql.Timestamp getmodified() { return modified;}
	 public String getcomments() { return comments;}
	 public java.math.BigDecimal getestimated_time() { return estimated_time;}
	 public int getcompletion() { return completion;}
	 public int gettolerance() { return tolerance;}
	 public String getcollect() { return collect;}
	 public int getid() { return id;}
	 public int gettopic() { return topic;}
	 public int getstatus() { return status;}
	 public java.math.BigDecimal getfare() { return fare;}
	 public String getdescription() { 
             if (description != null)
                return new String(description);
             else
                 return "";
         }     
         
         public String getpredecessorName() {
             return predecessorName;
         }         
	 public java.sql.Timestamp getdue_date() { return due_date;}
         public java.sql.Timestamp getreal_due_date() { return real_due_date;}
	 public int getreply_quotation_member() { return reply_quotation_member;}
	 public java.math.BigDecimal getactual_time() { return actual_time;}
	 public int getpriority() { return priority;}
	 public java.sql.Timestamp getassigned() { return assigned;}
	 public String getpublished() { return published;}
	 public java.sql.Timestamp getsend_quotation_date() { return send_quotation_date;}
	 public String getname() { return name;}
         public int getpredecessor() { return predecessor; }
         public String getpredecessor_required() { return predecessor_required; }         
         public int getmessage() { return message; } 
	 public String getOperation() { return operation; }
	 public String getsortColumn() { return sortColumn; }
	 public String getsortOrder() { return sortOrder; }
         public String getsource() { return source; }
	 public String getsortColumnAssignments() { return sortColumnAssignments; }
	 public String getsortOrderAssignments() { return sortOrderAssignments; }
	 public String getsortColumnFiles() { return sortColumnFiles; }
	 public String getsortOrderFiles() { return sortOrderFiles; }         
         public int    gettopic2task() { return topic2task; }
         public String getseverity() { return severity; }
         public int    gettype_task() { return type_task; }
         public String getspread_fix() { return spread_fix; }
         
         public void setpageFiles(int val) { pageFiles = val; }
         public int getpageFiles() { return pageFiles; }

         public void setpageAssignments(int val) { pageAssignments = val; }
         public int getpageAssignments() { return pageAssignments; }         
 
         // Regresa la descripcion en formato HTML
         public String getFormatedDescription() { 
             if (description != null) {
                 StringBuffer temp = new StringBuffer(new String(description));

                 // Los cambios de linea
                 int i = temp.indexOf("\\n");
                 while (i > 0) {
                     temp.replace(i,i+2, "<br>");
                     i = temp.indexOf("\\n");
                 }

                 // Los cambios de linea
                 i = temp.indexOf("\n");
                 while (i > 0) {
                     temp.replace(i,i+1, "<br>");
                     i = temp.indexOf("\n");
                 }


                // Los tabs tambien       
                i = temp.indexOf("\\t");
                 while (i > 0) {
                     temp.replace(i,i+2, "   ");
                     i = temp.indexOf("\\t");
                 }             

                // Los tabs tambien       
                i = temp.indexOf("\t");
                 while (i > 0) {
                     temp.replace(i,i+1, "   ");
                     i = temp.indexOf("\t");
                 }             

                 return temp.toString();
             } else {
                 return "";
             }
         }
                  
   /*
          * Se obtiene el campo de comentarios formateado en lineas de 100
          * caracteres
          */
         public String getFormatedComments() { 
             if (description != null) {
                 StringBuffer temp = new StringBuffer(new String(comments));

                 // Los cambios de linea
                 int len = temp.length(), i = 100;
                 while (i < len) {
                     temp = temp.insert(i, "<br>");               
                     i += 100;
                 }
      
                 return temp.toString();
             } else {
                 return "";
             }
         }        
         
	 /**
	 * Reset all properties to their default values.
	 *
	 * @param mapping The mapping used to select this instance
	 * @param request The servlet request we are processing
	 */
	 public void reset(ActionMapping mapping, HttpServletRequest request) {
		owner = 0;
		project = 1;
		start_date = null;
		reply_quotation_date = null;
		assigned_to = 0;
		created = null;
		modified = null;
		comments = "N/A";
		estimated_time = new BigDecimal(0);
		completion = 0;
		collect = "0";
		id = 0;
		topic = 0;
		status = 2;  // NOT STARTED
		fare = new BigDecimal(0);
		//description = "N/A".toCharArray();
                description = "N/A";
		due_date = null;
		reply_quotation_member = 0;
		actual_time = new BigDecimal(0);
		priority = 0;
		assigned = null;
		published = "0";
		send_quotation_date = null;
                predecessor = 0;
                predecessor_required = "0";
		name = "";
                severity = "0";
                type_task = 1;
                source = "";
		sortColumn = "status";
		sortOrder = "ASC";
		sortColumnAssignments = "owner";
		sortOrderAssignments = "DESC";
		sortColumnFiles = "name";
		sortOrderFiles = "DESC";                
                
                pageAssignments = 1;
                pageFiles = 1;
                topic2task = 0;
                spread_fix = " ";
	}

	 public String toString() {
		 return " owner:" + owner + " project:" + project + " start_date:" + start_date + " reply_quotation_date:" + reply_quotation_date + " assigned_to:" + assigned_to + " created:" + created + " modified:" + modified + " comments:" + comments + " estimated_time:" + estimated_time + " completion:" + completion + " tolerance:" + tolerance + " collect:" + collect + " id:" + id + " topic:" + topic + " status:" + status + " fare:" + fare + " description:" + description + " due_date:" + due_date + " reply_quotation_member:" + reply_quotation_member + " actual_time:" + actual_time + " priority:" + priority + " assigned:" + assigned + " published:" + published + " send_quotation_date:" + send_quotation_date + " name:" + name +
                    " check_monto_fijo: " + check_monto_fijo + " monto_manual: " + monto_manual + " severity:" + severity + " type_task:" + type_task; 
	 }

    public java.math.BigDecimal getEstimated_time_min() {
        return estimated_time_min;
    }

    public void setEstimated_time_min(java.math.BigDecimal estimated_time_min) {
        this.estimated_time_min = estimated_time_min;
    }

    /**
     * @return the finalizado
     */
    public int getFinalizado() {
        return finalizado;
    }

    /**
     * @param finalizado the finalizado to set
     */
    public void setFinalizado(int finalizado) {
        this.finalizado = finalizado;
    }

    /**
     * @return the emailNotifyTQA
     */
    public int getEmailNotifyTQA() {
        return emailNotifyTQA;
    }

    /**
     * @param emailNotifyTQA the emailNotifyTQA to set
     */
    public void setEmailNotifyTQA(int emailNotifyTQA) {
        this.emailNotifyTQA = emailNotifyTQA;
    }

    /**
     * @return the emailNotifyFQA
     */
    public int getEmailNotifyFQA() {
        return emailNotifyFQA;
    }

    /**
     * @param emailNotifyFQA the emailNotifyFQA to set
     */
    public void setEmailNotifyFQA(int emailNotifyFQA) {
        this.emailNotifyFQA = emailNotifyFQA;
    }

    public int getVersion_control() {
        return version_control;
    }

    public void setVersion_control(int version_control) {
        this.version_control = version_control;
    }

    public int getOperation_number() {
        return operation_number;
    }

    public void setOperation_number(int operation_number) {
        this.operation_number = operation_number;
    }

    public int getVerapp() {
        return verapp;
    }

    public void setVerapp(int verapp) {
        this.verapp = verapp;
    }

    public versionAppData getParentVerApp() {
        return parentVerApp;
    }

    public void setParentVerApp(versionAppData parentVerApp) {
        this.parentVerApp = parentVerApp;
    }    
}