//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.*;
import java.util.Date;
import org.apache.struts.validator.ValidatorActionForm;

/**
* Class that represent the form for the table topics
* @author Administrator
*/
public class topicsForm  extends ValidatorActionForm {

	 private String operation;
	 private String sortColumn;
	 private String sortOrder;
	 private int id;
	 private int owner;
	 private String totasks;
	 private int tasks;
	 private String status;
	 private String published;
	 private String subject;
         private String message;
         private String fromPage;
	 private java.sql.Timestamp last_post;
	 private int project;
	 private int posts;
         private int typeTopic;
         private String notified;

	 public void setid(int val) { id = val; } 
	 public void setowner(int val) { owner = val; } 
	 public void settotasks(String val) { totasks = val; } 
	 public void settasks(int val) { tasks = val; } 
	 public void setstatus(String val) { status = val; } 
	 public void setpublished(String val) { published = val; } 
	 public void setsubject(String val) { subject = val; } 
         public void setmessage(String val) { message = val; } 
	 public void setlast_post(java.sql.Timestamp val) { last_post = val; } 
	 public void setproject(int val) { project = val; } 
	 public void setposts(int val) { posts = val; } 
	 public void setOperation(String val) { operation =  val; }
	 public void setsortColumn(String val) { sortColumn =  val; }
	 public void setsortOrder(String val) { sortOrder =  val; }
         public void setfromPage(String val) { fromPage = val; }

	 public int getid() { return id;}
	 public int getowner() { return owner;}
	 public String gettotasks() { return totasks;}
	 public int gettasks() { return tasks;}
	 public String getstatus() { return status;}
	 public String getpublished() { return published;}
	 public String getsubject() { return subject;}
         public String getmessage() { return message;}
	 public java.sql.Timestamp getlast_post() { return last_post;}
	 public int getproject() { return project;}
	 public int getposts() { return posts;}
	 public String getOperation() { return operation; }
	 public String getsortColumn() { return sortColumn; }
	 public String getsortOrder() { return sortOrder; }
         public String getfromPage() { return fromPage; }
         
         public void settypeTopic(int val) { typeTopic = val; }
         public int  gettypeTopic() { return typeTopic; }             

           /**
          * Metodo que regresa la fecha y hora del ultimo post formateado.
          */
         public String getFormattedLastPost() {
             java.text.SimpleDateFormat format = new java.text.SimpleDateFormat("dd-MMM-yyyy HH:mm");
             
             try {
                return format.format(new Date(last_post.getTime()));
             } catch (Exception e) {
                 return "";
             }
         }
         
	 /**
	 * Reset all properties to their default values.
	 *
	 * @param mapping The mapping used to select this instance
	 * @param request The servlet request we are processing
	 */
	 public void reset(ActionMapping mapping, HttpServletRequest request) {
		id = 0;
		owner = 0;
		totasks = "";
		tasks = 0;
		status = "";
		published = "";
		subject = " ";
                message = " ";
		last_post = null;
		project = 0;
		posts = 0;
		sortColumn = "name";
		sortOrder = "DESC";
                fromPage = "";
                typeTopic = 1;
	}

	 public String toString() {
		 return " id:" + id + " owner:" + owner + " totasks:" + totasks + " tasks:" + tasks + " status:" + status + " published:" + published + " subject:" + subject + " last_post:" + last_post + " project:" + project + " posts:" + posts; 
	 }

    public String getnotified() {
        return notified;
    }

    public void setnotified(String notified) {
        this.notified = notified;
    }
}