//   Generated by FlechaRoja Tech Tools (2003) 

package com.unify.webcenter.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.*;
import org.apache.struts.validator.ValidatorActionForm;

/**
* Class that represent the form for the table task types
* @author Administrator
*/
public class type_tasksForm  extends ValidatorActionForm {
         private String operation;
	 private int id;
	 private String description;
         private String source;
         private String sortColumn;
         private String sortOrder;
         private int page;
         private String prefix;
         private String use_prefix;
         private int consecutive;      
         private int id_account;       
         
         public void setdescription(String val) { description = val; } 
	 public void setid(int val) { id = val; } 
	 public void setoperation(String val) { operation = val; }
         public void setsortOrder(String val) { sortOrder = val; }
         public void setsortColumn(String val) { sortColumn = val; }
         public void setpage(int val) { page = val; }
         public void setconsecutive(int val) { consecutive = val; } 
         public void setuse_prefix(String val) { use_prefix = val; } 
         public void setprefix(String val) { prefix = val; }          
         
	 public String getdescription() { return description; }
	 public int getid() { return id; }
	 public String getoperation() { return operation; }
         public String getsortOrder() { return sortOrder; }
         public String getsortColumn() { return sortColumn; }
         public int getpage() { return page; }
         public void setsource(String val) { source = val;}
         public String getsource() { return source; }
         public int getconsecutive() { return consecutive; } 
         public String getuse_prefix() { return use_prefix; } 
         public String getprefix() { return prefix; }           


         /**
	 * Reset all properties to their default values.
	 *
	 * @param mapping The mapping used to select this instance
	 * @param request The servlet request we are processing
	 */
	 public void reset(ActionMapping mapping, HttpServletRequest request) {
		description = "";
		id = 0;
                consecutive = 0;
		sortOrder = "DESC";
                sortColumn = "description";
                source = ""; 
                use_prefix = "1";
                prefix = "";
                
	}

	 public String toString() {
		 return " description:" + description + " id:" + id; 
	 }

    public int getId_account() {
        return id_account;
    }

    public void setId_account(int id_account) {
        this.id_account = id_account;
    }
}