--Accounts Data
Insert into ACCOUNTS
   (ID, NAME, DESCRIPTION, ADDRESS, PHONE_1, PHONE_2, EMAIL, USER_FARE, ACCOUNT_EMAIL, COMPANY, CREATOR, WEBSITE, ACTIVE, SHORTNAME, KEY_ENCRIPTATION)
 Values
   (1, 'DaytonaSoft', 'DaytonaSoft Administracion', 'Torre Mercedes', '22480802', '22480315', 'eduardo.gutierrez@daytonasoft.com', 0, 
'eduardo.gutierrez@daytonasoft.com', 'DAYTONASOFT', 'TMS SYSTEM DAYTONASOFT', 'www.daytonasoft.com', 'S', 'A', 'RCBNYpIMmQs69AiT7aWagQ==')
/

Insert into ACCOUNTS
   (ID, NAME, DESCRIPTION, ADDRESS, PHONE_1, PHONE_2, EMAIL, USER_FARE, ACCOUNT_EMAIL, COMPANY, CREATOR, WEBSITE, ACTIVE, SHORTNAME, KEY_ENCRIPTATION)
 Values
   (2, 'DaytonaSoft 2', 'DaytonaSoft Administracion 2', 'Torre Mercedes', '22480802', '22480315', 'eduardo.gutierrez@daytonasoft.com', 0, 
'eduardo.gutierrez@daytonasoft.com', 'DAYTONASOFT', 'TMS SYSTEM DAYTONASOFT', 'www.daytonasoft.com', 'S', 'A', 'RCBNYpIMmQs69AiT7aWagQ==')
/

--Countries Data
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(0, 'Default')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(1, 'Costa Rica')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(2, 'Mexico')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(3, 'Colombia')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(4, 'Argentina')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(5, 'Brazil')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(6, 'Chile')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(7, 'Ecuador')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(8, 'El Salvador')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(9, 'Guatemala')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(10, 'Honduras')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(11, 'Nicaragua')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(12, 'Panama')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(13, 'Peru')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(14, 'Puerto Rico')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(15, 'Republica Dominicana')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(16, 'Venezuela')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION)
  VALUES(17, 'USA')
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
  VALUES(18,'Afganistan');
/ 
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
  VALUES(19,'Islas Gland');
/  
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
  VALUES(20,'Albania');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(21,'Alemania');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(22,'Andorra');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(23,'Angola');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(24,'Anguilla');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(25,'Antartida');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(26,'Antigua y Barbuda');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(27,'Antillas Holandesas');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(28,'ArabiaSaudi');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(29,'Argelia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(31,'Aruba');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(32,'Australia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(33,'Austria');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(34,'Azerbaiyan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(35,'Bahamas');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(36,'Bahrein');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(37,'Bangladesh');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(38,'Barbados');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(39,'Bielorrusia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) 
VALUES(40,'Belgica');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(41,'Belice');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(42,'Benin');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(43,'Bermudas');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(44,'Bhutan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(45,'Bolivia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(46,'Bosnia y Herzegovina');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(47,'Botsuana');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(48,'Isla Bouvet');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(49,'Brunei');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(50,'Bulgaria');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(51,'Burkina Faso');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(52,'Burundi');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(53,'Cabo Verde');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(54,'Islas Caiman');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(55,'Camboya');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(56,'Camerun');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(57,'Canada');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(58,'Republica Centroafricana');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(59,'Chad');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(60,'Republica Checa');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(61,'China');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(62,'Chipre');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(63,'Isla de Navidad');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(64,'Ciudad del Vaticano');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(65,'Islas Cocos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(66,'Comoras');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(67,'Republica Democratica del Congo');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(68,'Congo');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(69,'Islas Cook');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(70,'Corea del Norte');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(71,'Corea del Sur');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(72,'Costa de Marfil');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(73,'Croacia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(74,'Cuba');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(75,'Dinamarca');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(76,'Dominica');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(77,'Republica Dominicana');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(78,'Egipto');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(79,'Emiratos Arabes Unidos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(80,'Eritrea');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(81,'Eslovaquia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(82,'Eslovenia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(83,'España');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(84,'Islas ultramarinas de Estados Unidos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(85,'Estados Unidos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(86,'Estonia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(87,'Etiopia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(88,'Islas Feroe');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(89,'Filipinas');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(90,'Finlandia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(91,'Fiyi');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(92,'Francia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(93,'Gabon');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(94,'Gambia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(95,'Georgia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(96,'Ghana');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(97,'Gibraltar');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(98,'Granada');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(99,'Grecia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(100,'Groenlandia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(101,'Guadalupe');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(102,'Guam');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(103,'Guayana Francesa');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(104,'Guinea');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(105,'Guinea Ecuatorial');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(106,'Guinea-Bissau');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(107,'Guyana');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(108,'Haiti');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(109,'Hong Kong');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(110,'Hungria');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(111,'India');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(112,'Indonesia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(113,'Iran');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(114,'Iraq');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(115,'Irlanda');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(116,'Islandia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(117,'Israel');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(118,'Italia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(119,'Jamaica');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(120,'Japon');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(121,'Jordania');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(122,'Kazajstan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(123,'Kenia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(124,'Kirguistan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(125,'Kiribati');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(126,'Kuwait');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(127,'Laos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(128,'Lesotho');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(129,'Letonia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(130,'Libano');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(131,'Liberia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(132,'Libia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(133,'Liechtenstein');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(134,'Lituania');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(135,'Luxemburgo');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(136,'Macao');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(137,'Madagascar');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(138,'Malasia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(139,'Malawi');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(140,'Maldivas');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(141,'Mali');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(142,'Malta');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(143,'Islas Malvinas');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(144,'Islas Marianas del Norte');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(145,'Marruecos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(146,'Islas Marshall');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(147,'Martinica');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(148,'Mauricio');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(149,'Mauritania');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(150,'Mayotte');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(151,'Micronesia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(152,'Moldavia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(153,'Monaco');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(154,'Mongolia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(155,'Montserrat');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(156,'Mozambique');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(157,'Myanmar');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(158,'Namibia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(159,'Nauru');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(160,'Nepal');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(161,'Niger');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(162,'Nigeria');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(163,'Niue');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(164,'Isla Norfolk');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(165,'Noruega');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(166,'Nueva Caledonia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(167,'Nueva Zelanda');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(168,'Oman');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(169,'Paises Bajos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(170,'Pakistan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(171,'Palau');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(172,'Palestina');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(173,'Papua Nueva Guinea');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(174,'Paraguay');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(175,'Islas Pitcairn');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(176,'Polinesia Francesa');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(177,'Polonia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(178,'Portugal');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(179,'Puerto Rico');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(180,'Qatar');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(181,'Reino Unido');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(182,'Ruanda');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(183,'Rumania');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(184,'Rusia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(185,'Sahara Occidental');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(186,'Islas Salomon');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(187,'Samoa');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(188,'Samoa Americana');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(189,'San Cristobal y Nevis');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(190,'San Marino');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(191,'San Pedro y Miquelon');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(192,'San Vicente y las Granadinas');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(193,'Santa Helena');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(194,'Santa Lucia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(195,'Santo Tome y Principe');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(196,'Senegal');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(197,'Serbia y Montenegro');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(198,'Seychelles');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(199,'Sierra Leona');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(200,'Singapur');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(201,'Siria');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(202,'Somalia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(203,'Sri Lanka');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(204,'Suazilandia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(205,'Sudafrica');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(206,'Sudan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(207,'Suecia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(208,'Suiza');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(209,'Surinam');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(210,'Tailandia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(211,'Taiwan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(212,'Tanzania');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(213,'Tayikistan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(214,'Timor Oriental');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(215,'Togo');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(216,'Tokelau');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(217,'Tonga');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(218,'Trinidad y Tobago');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(219,'Tunez');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(220,'Islas Turcas y Caicos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(221,'Turkmenistan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(222,'Turquia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(223,'Tuvalu');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(224,'Ucrania');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(225,'Uganda');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(226,'Uruguay');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(227,'Uzbekistan');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(228,'Vanuatu');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(229,'Venezuela');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(230,'Vietnam');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(231,'Islas Virgenes Britanicas');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(232,'Islas Virgenes de los Estados Unidos');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(233,'Wallis y Futuna');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(234,'Yemen');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(235,'Yibuti');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(236,'Zambia');
/
INSERT INTO COUNTRIES(COD_PAIS, DESCRIPTION) VALUES(237,'Zimbawe');  


Insert into ORGANIZATIONS
   (ID, COD_PAIS, NAME, ADDRESS1, PHONE, EMAIL, CREATED, ID_ACCOUNT)
 Values
   (1, 1, 'Daytonasoft', 'Torre Mercedes 8vo Piso', '22480802', 'eduardo.gutierrez@daytonasoft.com', TO_DATE(SYSDATE, 'MM/DD/YYYY HH24:MI:SS'), 1);

Insert into ORGANIZATIONS
   (ID, COD_PAIS, NAME, ADDRESS1, PHONE, EMAIL, CREATED, ID_ACCOUNT)
 Values
   (2, 1, 'Daytonasoft', 'Torre Mercedes 8vo Piso', '22480802', 'eduardo.gutierrez@daytonasoft.com', TO_DATE(SYSDATE, 'MM/DD/YYYY HH24:MI:SS'), 2);


--Members Data Pass 123456
Insert into MEMBERS
   (ID, ORGANIZATION, LOGIN, PASSWORD, NAME, TITLE, EMAIL_WORK, COMMENTS, PROFILE, CREATED, LOGOUT_TIME, LAST_PAGE, QUOTATION, PERSONAL_TITLE, REPORTS, TEMPLATE, COST, IND_CHECK_SCHEDULES, TIME_ZONE, ID_ACCOUNT, EXPIRED_DATE, RENEW_DATE, SALE_COST, IND_EXEC_REPORT)
 Values
   (1, 1, 'superadmin', '7C4A8D09CA3762AF61E59520943DC26494F8941B', 'Super Administrador', 'Super Admin', 'eduardo.gutierrez@daytonasoft.com', '-', '4', TO_DATE(SYSDATE, 'MM/DD/YYYY HH24:MI:SS'), 0, ' ', '0', ' ', '0', 'default', 0, '1', 'America/Costa_Rica', 1, TO_DATE('07/14/2010 12:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/14/2009 04:15:53', 'MM/DD/YYYY HH24:MI:SS'), 0, 'N')
/
Insert into MEMBERS
   (ID, ORGANIZATION, LOGIN, PASSWORD, NAME, TITLE, EMAIL_WORK, PHONE_HOME, MOBILE, FAX, PROFILE, CREATED, LOGOUT_TIME, LAST_PAGE, QUOTATION, PERSONAL_TITLE, REPORTS, TEMPLATE, COST, IND_CHECK_SCHEDULES, TIME_ZONE, ID_ACCOUNT, EXPIRED_DATE, RENEW_DATE, SALE_COST, IND_EXEC_REPORT)
 Values
   (2, 2, 'admin', '7C4A8D09CA3762AF61E59520943DC26494F8941B', 'Administrator', 'Admin', 'eduardo.gutierrez@daytonasoft.com', ' ', ' ', ' ', '3', TO_DATE(SYSDATE, 'MM/DD/YYYY HH24:MI:SS'), 0, ' ', '0', ' ', '0', 'default', 0, '1', 'America/Costa_Rica', 2, TO_DATE('07/14/2010 12:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/29/2009 11:33:28', 'MM/DD/YYYY HH24:MI:SS'), 0, 'S')
/

-- MAster Report Data
INSERT INTO MASTER_REPORT ( ID, NAME, DESCRIPTION ) VALUES ( 
1, 'Informe de Labores', 'Informe Labores')
/
INSERT INTO MASTER_REPORT ( ID, NAME, DESCRIPTION ) VALUES ( 
2, 'Informe  Global de Labores', 'Informe  Global de Labores')
/
