SET DEFINE OFF;
DROP USER TMS CASCADE;
 
CREATE USER TMS
  IDENTIFIED BY TMSSOCASE
  DEFAULT TABLESPACE TMS_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for TMS 
  GRANT RESOURCE TO TMS;
  GRANT CONNECT TO TMS;
  ALTER USER TMS DEFAULT ROLE ALL;
  -- 1 Tablespace Quota for TMS 
  ALTER USER TMS QUOTA UNLIMITED ON TMS_DATA;
  REVOKE UNLIMITED TABLESPACE FROM TMS;


