/*
 * Generated by Flecha Roja Technologies Auto Generator
 *
 * Created on January 9, 2003, 11:31 AM
 */
package com.unify.webcenter.action;

import com.unify.webcenter.broker.*;
import java.sql.Timestamp;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.servlet.*;
import javax.servlet.http.*;
import org.apache.commons.beanutils.PropertyUtils;
import org.apache.struts.action.*;

import com.unify.webcenter.data.loginData;
import com.unify.webcenter.data.membersData;
import com.unify.webcenter.data.organizationsData;
import com.unify.webcenter.form.membersForm;
import java.io.IOException;
import com.unify.webcenter.conf.TMSConfigurator;
import com.unify.webcenter.data.accountsData;
import com.unify.webcenter.data.projectsData;
import com.unify.webcenter.data.teamsData;
import com.unify.webcenter.tools.loadTimeZone;
import java.math.BigDecimal;
import java.util.ArrayList;
import org.apache.ojb.broker.util.BrokerHelper;

/**
 * <p>This action works with both JSP and Velocity templates.
 * The type of template to be used is defined in the Struts configuration
 * file.</p>
 *
 * <p>The action support an <i>action</i> URL parameter. This URL parameter
 * controls what this action class does. The following values are supported:</p>
 * <ul>
 *   <li>save    Save the record
 *   <li>delete	 Delete the record
 *   <li>edit    Edit the record
 *   <li>show	 Show the record
 * </ul>
 *
 *
 * @author Administrator 
 */
public class membersAction extends Action {

    private static Logger logger = Logger.getLogger("com.unify");

    /** Creates a new instance of calendarAction */
    public membersAction() {

    }

    /**
     * Handle server requests.
     *
     * @param mapping The ActionMapping used to select this instance
     * @param actionForm The optional ActionForm bean for this request (if any)
     * @param request The HTTP request we are processing
     * @param response The HTTP response we are creating
     *
     * @exception IOException if an input/output error occurs
     * @exception ServletException if a servlet exception occurs
     */
    public ActionForward execute(ActionMapping mapping,
                                    ActionForm form,
                                    HttpServletRequest request,
                                    HttpServletResponse response)
                                    throws IOException, ServletException {
        String action;
        HttpSession session;
        membersBroker broker;
        organizationsBroker orgBroker;
        projectsBroker projBroker;
        accountsBroker accountBroker;
        session = request.getSession(false);

        String company = null;
        String trial = null;
        String expirationsubscriptiondate= null;
        
        // Si la sesion es nula, se debe redireccionar al login.
        
        if (session == null || session.getAttribute("login") == null) {

            // forward to display the home page
            return (mapping.findForward("login"));

        } else {
            
            
            
            broker = new membersBroker();
            orgBroker = new organizationsBroker();
            projBroker = new projectsBroker();
            accountBroker = new accountsBroker();
            // Intanciar clase para el envio de correo
            com.unify.webcenter.tools.sendMail sm = new com.unify.webcenter.tools.sendMail();
            
            try {
                if (form == null) {
                    System.out.println(" Creating new membersForm bean under key " + mapping.getAttribute());
                    form = new membersForm();
                }

                
                // Se obtiene la referencia al loginData dentro de la session.
                loginData user = (loginData) session.getAttribute("login");
                TMSConfigurator tms = new TMSConfigurator(user);
                company = tms.getCompany(user);
                trial = tms.getTrial();
                        
                ActionErrors errors = new ActionErrors();

                // Se agrega al contexto la informacion del usuario
                request.setAttribute("userInfo", user);
     request.setAttribute("company", company);
                membersForm thisForm = (membersForm) form;
                // fetch action from form
                action = ((membersForm) form).getOperation();
                System.out.println(action);
                servlet.log("[DEBUG] membersAction at perform(): Action is " + action);
                String theDate;
                int userId;
                String emailList;
                // Determine what to do
                if (action == null || action.equals("listing") || action.equals("listing1") ||
                        action.equals("addmail") || action.equals("userlisting1"))  {
                        


                    
                    // Traer los valores para desplegar la lista de organizaciones disponibles.
                    // Constituye un listado completo y para ello nos valemos del broker.                                              
                    // Y por ultimo lo agregramos al contexto    
                    Iterator e = null;
                    membersData data= new membersData();
                     Calendar cal= Calendar.getInstance();
                     Calendar now= Calendar.getInstance();
                     
                    
                    if(action != null && action.equals("userlisting1")){
                        
                        
                        e = broker.getList("expired_date", "ASC", user.getId_account());
                        ArrayList usersSelected= new ArrayList();
                        if(request.getParameter("typeOf")==null || request.getParameter("typeOf").compareTo("1")==0)
                        {
                        request.setAttribute("typeOf", "1");
                        }else{
                            
                                if(request.getParameter("typeOf").equals("2")){
                                        request.setAttribute("typeOf", "2");
                                }else{
                                        request.setAttribute("typeOf", "3");
                                }
                            while (e.hasNext())
                            {
                                data= (membersData) e.next();
                                cal.setTime(data.getExpired_date());
                                if(request.getParameter("typeOf").equals("2")){
                                    if (cal.after(Calendar.getInstance()))
                                    {
                                        usersSelected.add(data);
                                    }
                                }else
                                {
                                    if (cal.before(Calendar.getInstance()))
                                    {
                                        usersSelected.add(data);
                                    }
                                }
                            }
                        e = usersSelected.iterator();
                        }
                        
                    }else{
                        
                    e = broker.getList("name", "ASC", user.getId_account());
                    }

                    ArrayList lista = new ArrayList();
                    boolean flag=true;
                    while (e.hasNext()) {
                        data = (membersData) e.next();
                        if (flag){now.setTime(data.getExpired_date()); flag=false;}
                        
                        data.setownercount(projBroker.getProjectCountByOwner(data.getid(), user.getId_account()));
                        lista.add(data);
                        cal.setTime(data.getExpired_date());
                        
                        if (now.before(cal)){
                            now.setTime(cal.getTime());
                        }
                    }
                    projBroker.close();
                    request.setAttribute("list", lista);

                    thisForm.setsortOrder("DESC");
                    
                    if (request.getParameter("page") != null) {
                        thisForm.setfromPage(request.getParameter("page").toString());
                        
                    }
                    if (action == null || action.equals("listing") || action.equals("listing1")|| action.equals("userlisting1")) {
                        //   optener parametros del dia y fecha 
                        // Se agrega el link para el menu con la ruta

                        request.setAttribute("menuRoute",
                                "<a href='./admin.do'>" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserAdmin"));
                        
                        // forward to display the list 
                        request.setAttribute("company", company);
                        if (action.equals("userlisting1"))
                        {
                                 request.setAttribute("menuRoute",
                                "<a href='./admin.do'>" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserRenew"));
                        
                                 
                            request.setAttribute("trial_date", "" + now.get(Calendar.YEAR) +
                            "-" + (now.get(Calendar.MONTH)+1 ) +
                            "-" + now.get(Calendar.DAY_OF_MONTH));
                            return (mapping.findForward("userListing"));
                            
                            
                        }else{
                            return (mapping.findForward("listing"));
                        }
                    } else {
                        theDate = request.getParameter("theDate");
                        request.setAttribute("theDate", theDate);
                        userId = Integer.parseInt(request.getParameter("userId"));
                        request.setAttribute("userId", "" + userId);
                        request.setAttribute("subject", request.getParameter("subject"));
                        request.setAttribute("description", request.getParameter("description"));
                        request.setAttribute("member", request.getParameter("member"));
                        request.setAttribute("id", request.getParameter("id"));
                        request.setAttribute("hour_start", request.getParameter("hour_start"));
                        request.setAttribute("hour_end", request.getParameter("hour_end"));
                        request.setAttribute("min_start", request.getParameter("min_start"));
                        request.setAttribute("min_end", request.getParameter("min_end"));
                        request.setAttribute("task", request.getParameter("task"));
                        request.setAttribute("emails", request.getParameter("emails"));
                        request.setAttribute("username", request.getParameter("username"));
                        request.setAttribute("operation1", request.getParameter("operation1"));

                        request.setAttribute("menuRoute",
                                "<a href='./home.do'>" +
                                java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" +
                                java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayCalendar"));
                        //+"</a>&nbsp;/&nbsp;"+ "calendar.do?"  );
                        request.setAttribute("company", company);
                        return (mapping.findForward("addemail"));
                    }

                } else if (action.equals("sort") || action.equals("sortRenew")) {
                    // Traer los valores para desplegar la lista de organizaciones disponibles.
                    // Constituye un listado completo y para ello nos valemos del broker.                                              
                    // Y por ultimo lo agregramos al contexto
                    Iterator e = broker.getList(thisForm.getsortColumn(),
                            thisForm.getsortOrder(), user.getId_account());

                    ArrayList lista = new ArrayList();
                    membersData data = new membersData();

                    if (action.equals("sortRenew"))
                    {
                     Calendar cal= Calendar.getInstance();
                     Calendar now= Calendar.getInstance();
                    ArrayList usersSelected= new ArrayList();
                        if(request.getParameter("typeOf")==null || request.getParameter("typeOf").compareTo("1")==0)
                        {
                        request.setAttribute("typeOf", "1");
                        }else{
                            
                                if(request.getParameter("typeOf").equals("2")){
                                        request.setAttribute("typeOf", "2");
                                }else{
                                        request.setAttribute("typeOf", "3");
                                }
                            while (e.hasNext())
                            {
                                data= (membersData) e.next();
                                cal.setTime(data.getExpired_date());
                                if(request.getParameter("typeOf").equals("2")){
                                    if (cal.after(Calendar.getInstance()))
                                    {
                                        usersSelected.add(data);
                                    }
                                }else
                                {
                                    if (cal.before(Calendar.getInstance()))
                                    {
                                        usersSelected.add(data);
                                    }
                                }
                            }
                        e = usersSelected.iterator();
                        }
                    
                    }
                    
                    while (e.hasNext()) {
                        data = (membersData) e.next();
                        data.setownercount(projBroker.getProjectCountByOwner(data.getid(), user.getId_account()));
                        lista.add(data);
                    }
                    request.setAttribute("list", lista);

                    // Negamos el tipo de ordenamiento
                    if (thisForm.getsortOrder().equalsIgnoreCase("ASC")) {
                        thisForm.setsortOrder("DESC");
                    } else {
                        thisForm.setsortOrder("ASC");
                    }
                    
                    if (action.equals("sortRenew"))
                    {
                        request.setAttribute("typeOf", request.getParameter("typeOf"));
                        request.setAttribute("trial_date", request.getParameter("trial_date"));
                            request.setAttribute("menuRoute",
                            "<a href='./admin.do'>" +
                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserRenew"));
                    }else{

                    // Se agrega el link para el menu con la ruta
                    request.setAttribute("menuRoute",
                            "<a href='./admin.do'>" +
                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserAdmin"));
                    }
                    // forward to display the list
                    request.setAttribute("company", company);
                    
                    if (action.equals("sort")){
                    return (mapping.findForward("listing"));
                    }else{
                    return (mapping.findForward("userListing"));
                    }

                } else if (action.equals("add")) {
                   
                    // En el caso de la operacion add, se despliega el formulario.
                    request.setAttribute("title",
                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.addMember"));
                    thisForm.setOperation("applyAdd");
                    thisForm.setid(0);
                    thisForm.setcreated(new Timestamp(Calendar.getInstance().getTimeInMillis()));
                    thisForm.setExpired_date(new java.sql.Timestamp(Calendar.getInstance().getTimeInMillis()));
                    thisForm.setCost(new BigDecimal(0));
                    // Se agrega al contexto la lista de organizaciones.                         
                    Iterator e = orgBroker.getList("name", "DESC", user.getId_account());

                    // Debemos convertir el iterador en un arraylist.
                    ArrayList lista = new ArrayList();
                    while (e.hasNext()) {
                        lista.add(e.next());
                    }
                    // Se guarda la lista de files asociados a esta tarea.
                    request.setAttribute("listOrganizations", lista);

                    //Toma las zona horaria
                    loadTimeZone timeZone = new loadTimeZone();
                    ArrayList listTimeZone = new ArrayList();
                    listTimeZone = timeZone.loadValues();

                    // Se guarda la lista de la Zona Horaria
                    request.setAttribute("listTimeZone", listTimeZone);
                    
                    
                    
                    //Subimos por request la cuenta con la que se va a crear el usuario
                    accountsData accountData = new accountsData();
                    accountData = (accountsData) accountBroker.getData(user.getId_account());
                    
                    
                   //Se define un Calendar.
                    Calendar now = Calendar.getInstance();
                    int month= (int)(now.get(Calendar.MONTH))+1;
                    int year= (int)(now.get(Calendar.YEAR));
                    if (month==12){
                        month=1;
                        year++;
                    }
                    
                    if(accountData.getFinal_trial_date()==null){
                         int trialDate=Integer.parseInt(TMSConfigurator.getTrial());

                        
                        request.setAttribute("fecha1", "" + year +
                                "-" +  ((int)(month) +  1) +
                                "-" + trialDate);
                        }else{
                        
                            String[] splitDate =  accountData.getFinal_trial_date().toString().split(" ");
                            String[] splitDate1= splitDate[0].split("-");

                        request.setAttribute("fecha1", "" + splitDate1[0] +
                                "-" + (splitDate1[1]) +
                                "-" + (splitDate1[2]));
                        }
                    
                    if (accountData.getShortname() != null) {
                        request.setAttribute("acc", accountData.getShortname() + "_");
                    }
                    
                    request.setAttribute("expiration_date",setAccountParameter(accountData.getId()));
                    
                    // Dependiendo de que pagina ha sido llamado, asi se despliega uno
                    // u otro formulario y menu.
                    if (thisForm.getfromPage().equals("organizationsView")) {
                        // Se debe traer la referencia a la organizacion a partir
                        // de donde se va a insertar.
                        organizationsData data = (organizationsData) orgBroker.getData(thisForm.getorganization(), user.getId_account());

                        // Se agrega el link para el menu con la ruta, correspondiente
                        // a agregar un miembro estando en el view de una organizacion
                        request.setAttribute("menuRoute",
                                "<a href='./organizations.do'>" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.ClientOrganizations") + "</a>&nbsp;/" +
                                "<a href='./organizations.do?operation=view&id=" +
                                data.getid() + "'>" +
                                data.getname() + "</a>&nbsp;/" +
                                "&nbsp;" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.addUser"));

                        request.setAttribute("company", company);

                        // Se redirecciona al formulario apropiado.                         
                        return (mapping.findForward("displayAddFormClient"));
                    } else {
                        request.setAttribute("fromPage", thisForm.getfromPage());

                        // Se agrega el link para el menu con la ruta
                        request.setAttribute("menuRoute",
                                "<a href='./admin.do'>" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserAdmin"));
                        request.setAttribute("company", company);
                        return (mapping.findForward("displayAddForm"));
                    }

                } else if (action.equals("edit") ) {
                    // Si se trata de un edit, se debe de cargar los datos del bean
                    // en el formulario.
                    
                    membersData data = (membersData) broker.getData(thisForm.getid(), user.getId_account());
                    
                    accountsData accountData = new accountsData();
                    accountData = (accountsData) accountBroker.getData(data.getId_account());

                    //We convert the date to the specific member timezone
                    //data.setcreated(Timestamp.valueOf(data.convTimeZone(data.getcreated(), user.getTime_zone())));
                    request.setAttribute("createdDate", data.convTimeZone(data.getcreated(), user.getTime_zone()));

                    request.setAttribute("title",
                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.editMember"));

                    
                    System.out.println(user.getId_account()) ;
                    // Se agrega al contexto la lista de organizaciones.                         
                    Iterator e = orgBroker.getList("name", "DESC", user.getId_account());
                    // Debemos convertir el iterador en un arraylist.
                    
                    ArrayList lista = new ArrayList();
                    while (e.hasNext()) {
                        lista.add(e.next());
                    }
                    
                    // Se guarda la lista de files asociados a esta tarea.
                    
                    request.setAttribute("listOrganizations", lista);
                    System.out.println("Dim: "+accountData.getShortname());
                    if (accountData.getShortname() != null) {
                        if (accountData.getShortname().compareTo("-")!=0){
                        //Realizamos un split para desplegar unicamente el usuario
                        String[] split = data.getlogin().split(accountData.getShortname() + "_");
                        data.setlogin(split[1].toString());
                        //Subimos por request la cuenta con la que se va a crear el usuario
                        request.setAttribute("acc", accountData.getShortname() + "_");
                        }
                    }
                    
                    // We copy all the properties from the form to the bean.
                    
                    PropertyUtils.copyProperties(thisForm, data);

                    System.out.println("COST: "+data.getCost());
                    thisForm.setCost(data.getCost());
                    //Toma las zona horaria
                    loadTimeZone timeZone = new loadTimeZone();
                    ArrayList listTimeZone = new ArrayList();
                    listTimeZone = timeZone.loadValues();
                    // Se guarda la lista de la Zona Horaria
                    request.setAttribute("listTimeZone", listTimeZone);
                    thisForm.setOperation("applyEdit");
                    //Se define un Calendar.
                    Calendar now = Calendar.getInstance();

                    java.text.DateFormat df = java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM);

                    thisForm.setExpiredDate(df.format(thisForm.getExpired_date()));

                    
                    now.setTime(thisForm.getExpired_date());
                    
                    request.setAttribute("fecha1", "" + now.get(Calendar.YEAR) +
                            "-" + (now.get(Calendar.MONTH) + 1) +
                            "-" + now.get(Calendar.DAY_OF_MONTH));

                    request.setAttribute("expiration_date",setAccountParameter(thisForm.getId_account()));
                    
                    // Abro el formulario de edicion dependiendo de si viene del view de una
                    // organizacion o si de cualquier forma es un usuario del cliente
                    if (thisForm.getfromPage().equals("organizationsView") ||
                            data.getprofile().equalsIgnoreCase("2")) {
                        // Se debe traer la referencia a la organizacion a partir
                        // de donde se va a insertar.
                        organizationsData dataOrg = (organizationsData) orgBroker.getData(thisForm.getorganization(), user.getId_account());
                        // Se agrega el link para el menu con la ruta, correspondiente
                        // a agregar un miembro estando en el view de una organizacion
                        request.setAttribute("menuRoute",
                                "<a href='./organizations.do'>" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.ClientOrganizations") + "</a>&nbsp;/" +
                                "<a href='./organizations.do?operation=view&id=" +
                                dataOrg.getid() + "'>" +
                                dataOrg.getname() + "</a>&nbsp;/" +
                                "&nbsp;<a href='./members.do?operation=view&id=" +
                                data.getid() + "'>" +
                                data.getname() + "</a>&nbsp;/&nbsp;" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.editMember"));


                        // Se despiega el formulario apropiado.
                        request.setAttribute("company", company);
                        
                        if (action.equals("edit")){
                            return (mapping.findForward("displayEditFormClient"));
                        }
                    } else {
                        request.setAttribute("theDate", request.getParameter("theDate"));
                        request.setAttribute("userId", request.getParameter("userId"));
                        request.setAttribute("fromPage", request.getParameter("fromPage"));
                        projectsData dataProj = null;
                        if (session.getAttribute("project") != null) {
                            dataProj = (projectsData) projBroker.getData(Integer.parseInt(session.getAttribute("project").toString()), user.getId_account());
                        }

                        if (thisForm.getfromPage().equals("preference")) {
                            request.setAttribute("menuRoute",
                                    "<a href='./home.do'>" +
                                    java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" +
                                    ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserAdmin") + "&nbsp;/&nbsp;" +
                                    user.gefullname());
                        } else {

                            if (thisForm.getfromPage().equals("project")) {
                                request.setAttribute("menuRoute",
                                        "<a href='./home.do'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/" +
                                        "<a href='./projects.do?operation=view&id=" +
                                        dataProj.getid() + "'>" +
                                        dataProj.getname() + "</a>&nbsp;/" + data.getname());
                            } else {
                                if (thisForm.getfromPage().equals("home")) {
                                    request.setAttribute("menuRoute",
                                            "<a href='./home.do'>" +
                                            java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" +
                                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserAdmin") + "&nbsp;/&nbsp;" +
                                            data.getname());
                                } else {
                                    request.setAttribute("menuRoute",
                                            "<a href='./admin.do'>" +
                                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserAdmin"));
                                }
                            }
                        }
                        request.setAttribute("company", company);
                        return (mapping.findForward("displayEditForm"));
                    }
                
                }else if (action.equals("view")) {

                    // Si se trata de un view, se debe de cargar los datos del bean
                    // en el formulario.
                    membersData data = new membersData();
                    if (request.getParameter("id") != null) {
                        thisForm.setid(Integer.parseInt(request.getParameter("id").toString()));
                    }

                    data = (membersData) broker.getData(thisForm.getid(), user.getId_account());


                    request.setAttribute("title",
                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.viewClientOrganization"));

                    //We convert the date to the specific member timezone
                    request.setAttribute("createdDate", data.convTimeZone(data.getcreated(), user.getTime_zone()));

                    // We copy all the properties from the form to the bean.
                    PropertyUtils.copyProperties(thisForm, data);

                    if (request.getParameter("page") != null) {
                        thisForm.setfromPage(request.getParameter("page").toString());
                    }

                    //Se define un Calendar.
                    Calendar now = Calendar.getInstance();

                    java.text.DateFormat df = java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM);

                    thisForm.setExpiredDate(df.format(data.getExpired_date()));

                    now.setTime(data.getExpired_date());
                    request.setAttribute("fecha1", "" + now.get(Calendar.YEAR) +
                            "-" + (now.get(Calendar.MONTH) + 1) +
                            "-" + now.get(Calendar.DAY_OF_MONTH));

                    thisForm.setOperation("view");

                    // Se debe traer la referencia a la organizacion a partir
                    // de donde se va a insertar.

                    projectsData dataProj = new projectsData();

                    System.out.println(thisForm.getorganization());
                    organizationsData dataOrg = (organizationsData) orgBroker.getData(thisForm.getorganization(), user.getId_account());


                    if (request.getParameter("project") != null) {
                        dataProj = (projectsData) projBroker.getData(Integer.parseInt(request.getParameter("project").toString()), user.getId_account());
                    }
                    // Se agrega el link para el menu con la ruta, correspondiente
                    // a agregar un miembro estando en el view de una organizacion

                    // Se agrega el link para el menu con la ruta, correspondiente
                    // a agregar un miembro estando en el view de una organizacion
                    if (thisForm.getfromPage().equals("search")) {
                        boolean band = false;
                        if (!user.isAdmin()) {
                            teamsBroker team = new teamsBroker();
                            Iterator t = team.getListProjectsUser(data.getid(), data.getId_account());
                            teamsData tempTeam = new teamsData();

                            while (t.hasNext() && !band) {
                                tempTeam = (teamsData) t.next();
                                if (team.isMember(tempTeam.getprojects(), user.getid(), user.getId_account())) {
                                    band = true;
                                }
                            }
                            team.close();
                            if (band) {
                                request.setAttribute("menuRoute",
                                        "<a href='./home.do'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/" +
                                        data.getname());
                            } else {
                                // No hay acceso, se redirecciona a una pagina donde se le notifica
                                // de eso.
                                // Se agrega el link para el menu con la ruta
                                request.setAttribute("menuRoute",
                                        "<a href='./home.do'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/");
                                return (mapping.findForward("accessDenied"));
                            }
                        } else {
                            request.setAttribute("menuRoute",
                                    "<a href='./home.do'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/" +
                                    data.getname());
                        }
                    } else {
                        if (thisForm.getfromPage().equals("projectTeam")) {
                            request.setAttribute("menuRoute",
                                    "<a href='./home.do'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/" +
                                    "<a href='./projects.do?operation=view&id=" +
                                    dataProj.getid() + "'>" +
                                    dataProj.getname() + "</a>&nbsp;/" + data.getname());

                        } else {
                            if (thisForm.getfromPage().equals("preference") || thisForm.getfromPage().equals("home")) {
                                request.setAttribute("menuRoute",
                                        "<a href='./home.do'>" +
                                        java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" +
                                        data.getname());

                            } else {
                                if (thisForm.getfromPage().equals("admin")) {

                                    request.setAttribute("menuRoute",
                                            "<a href='./admin.do'>" +
                                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                                            ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserAdmin") + "&nbsp;/&nbsp;" +
                                            data.getname());
                                           

                                } else {
                                    if (thisForm.getfromPage().equals(" ") || thisForm.getfromPage().equals("")|| thisForm.getfromPage().equals(null)){
                                        request.setAttribute("menuRoute",
                                                    "<a href='./home.do'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/" +
                                                     "<a href='./members.do?operation=userlisting1'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserRenew") + "</a>&nbsp;/" +
                                                   data.getname());
                                    }else{
                                    
                                    if (!thisForm.getfromPage().equals("organizationsView")) {
                                      
                                            thisForm.setfromPage("project");
                                            session.setAttribute("project", String.valueOf(dataProj.getid()));

                                            // Se agrega el link para el menu con la ruta
                                            request.setAttribute("menuRoute",
                                                    "<a href='./home.do'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/" +
                                                    "<a href='./projects.do?operation=view&id=" +
                                                    dataProj.getid() + "'>" +
                                                    dataProj.getname() + "</a>&nbsp;/" + data.getname());

                                    } else {

                                        request.setAttribute("menuRoute",
                                                "<a href='./organizations.do'>" +
                                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.ClientOrganizations") + "</a>&nbsp;/" +
                                                "<a href='./organizations.do?operation=view&id=" +
                                                dataOrg.getid() + "'>" +
                                                dataOrg.getname() + "</a>&nbsp;/" +
                                                "&nbsp;" + data.getlogin());
                        
                                    }
                                    
                                    }
                                }
                            }
                        }
                    }

                    request.setAttribute("company", company);


                    return (mapping.findForward("displayViewForm"));

                } else if (action.equals("delete")) {
                    // Tomamos el bean correspondiente a este objeto a fin
                    // de proceder con su borrado

                    // get the string with ids separate by "," character, and split in array os strings
                    String[] fields = (request.getParameter("checkedItems") + ",").split(",");
                    ArrayList items = broker.getItems(fields, user.getId_account());

                    request.setAttribute("fromPage", request.getParameter("fromPage"));

                    request.setAttribute("param", "");
                    request.setAttribute("checkedItems", request.getParameter("checkedItems"));
                    request.setAttribute("items", items);
                    request.setAttribute("title",
                            ResourceBundle.getBundle("ApplicationResources",
                            new Locale(user.getlanguage(), "")).getString("common.Members"));
                    request.setAttribute("do", request.getRequestURI());
                    request.setAttribute("company", company);
                    // forward to display the list 
                    return (mapping.findForward("confirmDelete"));

                } else if (action.equals("applyDelete")) {
                    // Tomamos el bean correspondiente a este objeto a fin
                    // de proceder con su borrado

                    String[] fields = (request.getParameter("checkedItems") + ",").split(",");
                    String lista = "";
                    for (int i = 0; i < fields.length; i++) {
                        lista += fields[i] + " - ";
                    }
                    ArrayList items = broker.getItems(fields, user.getId_account());

                    // Se procede con el borrado de cada una de ellas.
                    membersData data;
                    projectsBroker projBroker2 = new projectsBroker();
                    tasksBroker tskBroker = new tasksBroker();
                    for (int i = 0; i < items.size(); i++) {
                        data = (membersData) items.get(i);
                        /* BORRAR UN MEMBER IMPLICA ELIMINAR REFERENCIAS EN MULTIPLES TABLAS 
                         * El unico cuidado especial es a nivel projects y tasks en donde el admin
                         * de previo a decidido si se borran o se dejan en no asignados.
                         */
                        // Si es el usuario admin, NO se borra OJO... 
                        //if (data.getid() == 1) {
                        if ((!user.getprofile().equals("4") && !user.getprofile().equals("3"))) {
                            errors.add("ownerconflict", new ActionError("errors.cannotDeleteAdmin.wrong"));
                            saveErrors(request, errors);
                        } else {
                            if (projBroker2.getProjectCountByOwner(data.getid(), user.getId_account()) > 0) {
                                errors.add("ownerconflict", new ActionError("errors.cannotDeleteProjectOwner.wrong"));
                                saveErrors(request, errors);
                            } else if (tskBroker.getTotalTasksByMember(data.getid(), user.getId_account()) > 0) {
                                errors.add("userconflict", new ActionError("errors.cannotDeleteTasksOwner.wrong"));
                                saveErrors(request, errors);
                            } else {
                                // Se borran todas las referencias
                                System.out.println("deleting " + data.getname());
                                broker.deleteAllReferences(data.getid(), data.getprofile(), user.getId_account());
                            }
                        }
                    }

                    // Se cierra el broker
                    tskBroker.close();
                    projBroker2.close();

                    if (!errors.isEmpty()) {
                        // Si hay errores se le despliegan al usuario
                        return (new ActionForward(mapping.findForward("listingWithErrors").
                                getPath() + "?operation=listing"));
                    } else {
                        // No hay errores, se redirecciona a la pagina pertinente.
                        if (thisForm.getfromPage().equals("home")) {
                            request.setAttribute("menuRoute",
                                    "<a href='./home.do'>" +
                                    java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" + user.gefullname());

                            return (mapping.findForward("home"));
                        } else {
                            // Y por ultimo lo agregramos al contexto para que el usuario vea
                            // la lista actualizada.
                            Iterator e = broker.getList("name", "ASC", user.getId_account());
                            ArrayList listaOut = new ArrayList();
                            data = new membersData();

                            while (e.hasNext()) {
                                data = (membersData) e.next();
                                data.setownercount(projBroker.getProjectCountByOwner(data.getid(), user.getId_account()));
                                listaOut.add(data);
                            }
                            projBroker.close();
                            request.setAttribute("list", listaOut);

                            thisForm.setsortOrder("DESC");

                            request.setAttribute("menuRoute",
                                    "<a href='./admin.do'>" +
                                    ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                                    ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.UserAdmin"));

                            if (Integer.parseInt(user.getprofile()) == 3) {
                                request.setAttribute("company", company);
                                // forward to display the list solo para el administrador
                                return (mapping.findForward("listing"));
                            } else {
                                request.setAttribute("company", company);
                                return (mapping.findForward("listing"));
                            // forward to display the view        
                                /*return (new ActionForward(mapping.findForward("displayViewForm").getPath() +
                            "?operation=view&id=" + thisForm.getid()));*/
                            }
                        }
                    }
                } else if (action.equals("applyAdd")) {
                    // Se validan los datos ingresados
                    errors = thisForm.validate(mapping, request);
                    String rePassword = request.getParameter("repassword");

                    if (rePassword == null) {
                        rePassword = "";
                    }
                    
                    if (errors.isEmpty() && thisForm.getpassword().equals(rePassword)) {

                        // Se trata de la aplicacion de un insert en la BD
                        membersData data = new membersData();
                        accountsData accountData = new accountsData();
                        // We copy all the properties from the form to the bean.
                        //   data.setcomments(thisForm.getcomments());
                        //        data.setcomments(thisForm.getcomments());
                        PropertyUtils.copyProperties(data, thisForm);

                        data.setId_account(user.getId_account());

                        accountData = (accountsData) accountBroker.getData(data.getId_account());
                        
                        data.setSale_cost(accountData.getUser_fare());
          
                        
                        //Concatenamos el login con el diminutivo de la cuenta
                        if (accountData.getShortname().startsWith("-")) {
                            data.setlogin(data.getlogin());
                        }else{
                            data.setlogin(accountData.getShortname() + "_" + data.getlogin());
                        }
                        
                        if (broker.exists(data.getlogin())) {
                            // Ya existe un usuario con ese login, no se puede continuar.
                            // Se detecto un error de validacion, se retorna    
                            
                            errors.add("loginConflict", new ActionError("errors.loginConflict"));
                            saveErrors(request, errors);
                            request.setAttribute("company", company);
                            return (new ActionForward(mapping.findForward("displayAddFormError").
                                    getPath() + "?operation=add"));

                        } else {
                            // We set the create date & time´
                            data.setcreated(new Timestamp(Calendar.getInstance().getTimeInMillis()));
                            data.setRenew_date(new java.sql.Timestamp(Calendar.getInstance().getTimeInMillis()));
                            data.setTemplate("default");
                            data.setExpired_date(thisForm.getExpired_date());
                            
                                if (data.getCost().equals(null)){
                                    data.setCost(new BigDecimal(0));
                                }
                                                        
                                if (data.getSale_cost().equals(null)){
                                    data.setSale_cost(new BigDecimal(0));
                                }
                            // We add the new record and set the password
                            String pass = data.getpassword();
                            data.setpassword(membersData.encrypt(data.getpassword()));


                            broker.add(data);
                            
                            // Se envia un correo avisandole al usuario
                            sm.send("newUser", data, data, data.getid(), pass, user, String.valueOf(session.getAttribute("mainUrl")));

                            // Si estamos desde la perspectiva de una organizacion, lo redireccionamos
                            // ahi
                            if (thisForm.getfromPage().equals("organizationsView")) {
                                request.setAttribute("company", company);
                                return (new ActionForward(mapping.findForward("viewingProjects").
                                        getPath() + "?operation=view&id=" + data.getorganization()));

                            } else if (thisForm.getfromPage().equals("home")) {
                                request.setAttribute("menuRoute",
                                        "<a href='./home.do'>" +
                                        java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" + user.gefullname());
                                request.setAttribute("company", company);
                                return (mapping.findForward("home"));
                            } else {
                                // Sino, pues mostramos la lista general.
                                Iterator e = broker.getList("name", "ASC", user.getId_account());
                                ArrayList lista = new ArrayList();
                                data = new membersData();

                                while (e.hasNext()) {
                                    data = (membersData) e.next();
                                    data.setownercount(projBroker.getProjectCountByOwner(data.getid(), user.getId_account()));
                                    lista.add(data);
                                }
                                projBroker.close();
                                request.setAttribute("list", lista);
                                thisForm.setsortOrder("DESC");

                                // Disponemos la ruta general.
                                request.setAttribute("menuRoute",
                                        "<a href='./members.do'>" +
                                        ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" +
                                        ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Members"));
                                request.setAttribute("company", company);
                                return (mapping.findForward("listing"));
                            }
                        }
                    } else {
                        // Se detecto un error de validacion, se retorna
                        if (thisForm.getpassword().equals(rePassword) == false) {
                            errors.add("password", new ActionError("errors.passwordNotMatch"));
                        }

                        saveErrors(request, errors);
                        request.setAttribute("company", company);
                        return (new ActionForward(mapping.findForward("displayAddFormError").
                                getPath() + "?operation=add"));
                    }

                } else if (action.equals("applyEdit")) {
                    
                    
                    // Se validan los datos ingresados
                    errors = thisForm.validate(mapping, request);
                    
                    String rePassword = request.getParameter("repassword");
                    boolean passChanged = false;
                    boolean emailChanged = false;
                    boolean loginChanged = false;
                    if (rePassword == null) {
                        rePassword = "";
                    }

                    if (errors.isEmpty() && thisForm.getpassword().equals(rePassword)) {
                        // Se trata de la aplicacion de un update en la BD
                        membersData data = new membersData();
                        accountsData accountData = new accountsData();
                        // We copy all the properties from the form to the bean.

                        PropertyUtils.copyProperties(data, thisForm);
                        data.setId_account(user.getId_account());
                        accountData = (accountsData) accountBroker.getData(data.getId_account());

                        // Se obtiene la referencia al loginData dentro de la session
                        // y se actualiza el template que usa
                        user = (loginData) session.getAttribute("login");

                        // Link de los members a ver si se cambio o no la clave
                        membersData oldData = (membersData) broker.getData(data.getid(), user.getId_account());

                        user.setTemplate(oldData.getTemplate());

                        // Se agrega al contexto la informacion del usuario
                        request.setAttribute("userInfo", user);

                        String pass = null;

                        // Si la clave vieja es diferente de la nueva
                        if (oldData.getpassword().equalsIgnoreCase(thisForm.getpassword()) == false) {
                            pass = thisForm.getpassword();
                            data.setpassword(membersData.encrypt(data.getpassword()));
                            passChanged = true;
                        }
                        
                        //Concatenamos el login con el diminutivo de la cuenta
                        if (accountData.getShortname() != null){
                            if (accountData.getShortname().compareTo("-")!=0){
                                thisForm.setlogin(accountData.getShortname().concat("_"+thisForm.getlogin()));
                                data.setlogin(accountData.getShortname() + "_" + data.getlogin());
                            }
                        }
                        
                        if (oldData.getlogin().equalsIgnoreCase(thisForm.getlogin()) == false) {
                            
                            if (broker.exists(data.getlogin())) {
                                // Ya existe un usuario con ese login, no se puede continuar.
                                // Se detecto un error de validacion, se retorna                            
                                errors.add("loginConflict", new ActionError("errors.loginConflict"));
                                saveErrors(request, errors);
                                request.setAttribute("company", company);
                                return (new ActionForward(mapping.findForward("displayAddFormError").
                                        getPath() + "?operation=add"));

                            } else {
                                loginChanged = true;
                            }
                        }
                        if (oldData.getemail_work().equalsIgnoreCase(thisForm.getemail_work()) == false) {
                            emailChanged = true;
                        }


                        loginData login = (loginData) session.getAttribute("login");
                        login.setTime_zone(data.getTime_zone());
                        
                            //Se define un Calendar.
                        Calendar now = Calendar.getInstance();
                        
                        now.set(Calendar.HOUR, 00);
                        now.set(Calendar.DATE, 00);
                        now.set(Calendar.SECOND, 00);
                        now.set(Calendar.MILLISECOND, 00);
                        
                        data.setRenew_date(new java.sql.Timestamp(Calendar.getInstance().getTimeInMillis()));

                    

                        java.text.DateFormat df = java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM);

                        now.setTime(data.getExpired_date());

                        request.setAttribute("fecha1", "" + now.get(Calendar.YEAR) +
                                "-" + (now.get(Calendar.MONTH) + 1) +
                                "-" + now.get(Calendar.DAY_OF_MONTH));


                        if (!user.getprofile().equals("3") && !user.getprofile().equals("4")) {
                            data.setorganization(oldData.getorganization());
                            data.setind_check_schedules(oldData.getind_check_schedules());
                            data.setExpired_date(oldData.getExpired_date());
                            data.setcomments(oldData.getcomments());
                            data.setSale_cost(oldData.getSale_cost());
                            data.setCost(oldData.getCost());
                        }
                        //Set the template
                        data.setTemplate(oldData.getTemplate());
                        login.setTemplate(data.getTemplate());
                        
                        // We add the new record.
                        broker.update(data);

                        session.setAttribute("login", login);
                        request.setAttribute("createdDate", data.convTimeZone(data.getcreated(), user.getTime_zone()));

                        if (passChanged) // Se envia un correo avisandole al usuario
                        {
                            sm.send("alterUserPass", data, data, data.getid(), pass, user,String.valueOf(session.getAttribute("mainUrl")));
                        }

                        if (emailChanged || loginChanged) // Se envia un correo avisandole al usuario
                        {
                            sm.send("alterUser", data, data, data.getid(), pass, user,String.valueOf(session.getAttribute("mainUrl")));
                        }


                        request.setAttribute("company", company);
                        if (thisForm.getfromPage().equals("organizationsView")) {
                            request.setAttribute("company", company);
                            return (new ActionForward(mapping.findForward("viewingProjects").
                                    getPath() + "?operation=view&id=" + data.getorganization()));

                        } else if (thisForm.getfromPage().equals("home")) {
                            request.setAttribute("menuRoute",
                                    "<a href='./home.do'>" +
                                    java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" + user.gefullname());

                            return (mapping.findForward("home"));
                        } else if (thisForm.getfromPage().equals("preference")) {
                            request.setAttribute("menuRoute",
                                    "<a href='./home.do'>" +
                                    java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" +
                                    user.gefullname());
                            return (new ActionForward(mapping.findForward("displayViewForm").getPath() +
                                    "?operation=view&id=" + thisForm.getid()));
                        } else {
                            projectsData dataProj = null;
                            if (session.getAttribute("project") != null) {
                                dataProj = (projectsData) projBroker.getData(Integer.parseInt(session.getAttribute("project").toString()), user.getId_account());
                            }
                            if (thisForm.getfromPage().equals("project")) {
                                request.setAttribute("menuRoute",
                                        "<a href='./home.do'>" + java.util.ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/" +
                                        "<a href='./projects.do?operation=view&id=" +
                                        dataProj.getid() + "'>" +
                                        dataProj.getname() + "</a>&nbsp;/" + data.getname());
                                return (new ActionForward(mapping.findForward("displayViewForm").getPath() +
                                        "?operation=view&id=" + thisForm.getid()));
                            } else {
                                // Se esta haciendo la edicion desde el view de una organizacion
                                // Y por ultimo lo agregramos al contexto para que el usuario vea
                                // la lista actualizada.
                                Iterator e = broker.getList("name", "ASC", user.getId_account());
                                ArrayList lista = new ArrayList();
                                data = new membersData();

                                while (e.hasNext()) {
                                    data = (membersData) e.next();
                                    data.setownercount(projBroker.getProjectCountByOwner(data.getid(), user.getId_account()));
                                    lista.add(data);
                                }
                                projBroker.close();
                                request.setAttribute("list", lista);
                                thisForm.setsortOrder("DESC");

                                // Se agrega el link para el menu con la ruta
                                request.setAttribute("menuRoute",
                                        "<a href='./members.do'>" + ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("header.displayStart") + "</a>&nbsp;/&nbsp;" +
                                        ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Members"));

                                if (Integer.parseInt(user.getprofile()) == 3 || Integer.parseInt(user.getprofile()) == 4) {
                                    // forward to display the list solo para el administrador
                                    request.setAttribute("company", company);
                                    return (mapping.findForward("listing"));
                                } else {
                                    request.setAttribute("company", company);
                                    // forward to display the view        
                                    return (new ActionForward(mapping.findForward("displayViewForm").getPath() +
                                            "?operation=view&id=" + thisForm.getid()));
                                }
                            }
                        }
                    } else {
                        // Se detecto un error de validacion, se retorna                       
                        if (thisForm.getpassword().equals(rePassword) == false) {
                            errors.add("password", new ActionError("errors.passwordNotMatch"));
                        }
                        saveErrors(request, errors);
                        request.setAttribute("company", company);
                        return (new ActionForward(mapping.findForward("displayAddFormError").
                                getPath() + "?operation=edit"));
                    }
                }  else if (action.equals("editExp")) {
                     
                    membersData data = new membersData();
                    membersBroker memberBroker= new membersBroker();
                    
                    
                    String month= request.getParameter("trial_date");
                    
                    String []date= month.split("-");
                    String[] fields = (request.getParameter("checkedItems") + ",").split(",");
                    Calendar now= Calendar.getInstance();
                    Calendar cal= Calendar.getInstance();
                    
                    now.set(Calendar.YEAR, Integer.parseInt(date[0]));
                         now.set(Calendar.MONTH, Integer.parseInt(date[1])-1);
                         now.set(Calendar.DAY_OF_MONTH, Integer.parseInt(date[2]));
                         now.set(Calendar.HOUR,00);
                         now.set(Calendar.MINUTE,00);
                         now.set(Calendar.SECOND, 00);
                         now.set(Calendar.MILLISECOND,00);
                    for (int i=0; i<fields.length; i++){
                        data = new membersData();
                        data= (membersData)memberBroker.getData(Integer.parseInt(fields[i]));
                        
                        data.setExpired_date(new Timestamp (now.getTimeInMillis()));
                        
                        broker.update(data);
                    }
                    
                    request.setAttribute("trial_date", "" + now.get(Calendar.YEAR) +
                    "-" + (now.get(Calendar.MONTH)+1 ) +
                    "-" + now.get(Calendar.DAY_OF_MONTH));
                    
                    
                        Iterator e = broker.getList("expired_date", "ASC", user.getId_account());
                        ArrayList usersSelected= new ArrayList();
                        
                            while (e.hasNext())
                            {
                                data= (membersData) e.next();
                                cal.setTime(data.getExpired_date());
                                if (request.getParameter("typeOf").equals("2"))
                                {
                                    if (Calendar.getInstance().before(cal))
                                    {
                                        usersSelected.add(data);
                                    }
                                }else if (request.getParameter("typeOf").equals("3"))
                                {  
                                    if (Calendar.getInstance().after(cal))
                                    {
                                        usersSelected.add(data);
                                    }
                                }else
                                {
                                    usersSelected.add(data);
                                }
                            }
                        
                    projBroker.close();

                    request.setAttribute("list", usersSelected);
                    request.setAttribute("typeOf", request.getParameter("typeOf"));
                    thisForm.setsortOrder("DESC");

                    if (request.getParameter("page") != null) {
                        thisForm.setfromPage(request.getParameter("page").toString());
                    }
                        //   optener parametros del dia y fecha 
                        // Se agrega el link para el menu con la ruta

                        request.setAttribute("menuRoute",
                                "<a href='./admin.do'>" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Administration") + "</a>&nbsp;/&nbsp;" +
                                ResourceBundle.getBundle("ApplicationResources", new Locale(user.getlanguage(), "")).getString("common.Renew"));

                        // forward to display the list 
                        request.setAttribute("company", company);
                        
                        return (mapping.findForward("userListing"));
                        
                }else if (action.equals("applyAddEmail")) {
                

                    String[] fields = (request.getParameter("checkedItems") + ",").split(",");
                    ArrayList items = broker.getItems(fields, user.getId_account());
                    userId = Integer.parseInt(request.getParameter("userId"));
                    theDate = request.getParameter("theDate");
                    String lista = "";

                    request.setAttribute("userId", "" + userId);
                    request.setAttribute("subject", request.getParameter("subject"));
                    request.setAttribute("description", request.getParameter("description"));
                    request.setAttribute("member", request.getParameter("member"));
                    request.setAttribute("id", request.getParameter("id"));
                    request.setAttribute("hour_start", request.getParameter("hour_start"));
                    request.setAttribute("hour_end", request.getParameter("hour_end"));
                    request.setAttribute("min_start", request.getParameter("min_start"));
                    request.setAttribute("min_end", request.getParameter("min_end"));
                    request.setAttribute("task", request.getParameter("task"));
                    request.setAttribute("username", request.getParameter("username"));
                    // Presenta la lista de contactos.
                    membersData data;
                    String listemail[] = new String[items.size()];
                    for (int i = 0; i < items.size(); i++) {
                        data = (membersData) items.get(i);
                        listemail[i] = data.getname() + " <" + data.getemail_work() + ">";
                        if (i != (items.size() - 1)) {
                            lista += "" + data.getid() + ";";
                        } else {
                            lista += "" + data.getid();
                        }
                    }
                    request.setAttribute("listContacts", listemail);
                    request.setAttribute("emails", lista);
                    request.setAttribute("company", company);
                    return (new ActionForward(mapping.findForward("addemailContaing").getPath() +
                            "?operation=addEvent1&userId=" + userId + "&theDate=" + theDate +
                            "&emails=" + lista.trim() + "&listaContacts=" + listemail));
                }
            } catch (Exception e) {
                servlet.log("[ERROR] Action at final catch: " + e.getMessage());
                logger.logp(Level.SEVERE, "members.do", "perform",
                        "Fatal Error: " + e.toString());

                e.printStackTrace();

            } finally {
                // Se cierran los brokers creados
                broker.close();
                orgBroker.close();
                projBroker.close();
                accountBroker.close();
            }
        }
   
        // Default if everthing else fails
        return (mapping.findForward("listing"));
    }

    // Retorna la lista de organizaciones 
    private ArrayList getListing(String sortCol, String sortOrder, membersBroker broker, int accountId) {
        Iterator e;
        // Se obtiene el iterador sobre todos los elementos de la lista.

        e = broker.getListofCompanyMembers(sortCol, sortOrder, 0, accountId);

        // Debemos convertir el iterador en un arraylist.
        ArrayList lista = new ArrayList();
        while (e.hasNext()) {
            lista.add(e.next());
        }

        return lista;
    }
    
    private Object setAccountParameter(int idAccount)
    {
        
        accountsData accountdata= new accountsData();
        accountsBroker accountbroker= new accountsBroker();
        
        Iterator e= accountbroker.getList(idAccount);
        
        accountdata=(accountsData) e.next();
        if (accountdata.getFinal_trial_date()!=null)
        {
            return accountdata.getFinal_trial_date();
        } else
        {
            return " ";
        }
    }
    

}
