/*
 * StringManipulator.java
 *
 * Created on April 10, 2005, 7:52 PM
 */

package com.unify.webcenter.tools;

/**
 *
 * @author  Gerardo Arroyo
 */
public final class StringManipulator {
     public static final char[] invalidFileCharactersArray = { '\\', '/', ':', '*', '?', '\'', '<', '>', '|', 'Á', 
     'É', 'Í', 'Ó', 'Ú', 'Ñ', 'ñ', 'á', 'é', 'í', 'ó', 'ú' };

    /** Creates a new instance of StringManipulator */
    private StringManipulator() {
    }
 
/** Generates a valid filename from the given filename, 
  * replacing invalid characters with the specified character.
  * If the specified replacement character is itself invalid, this method 
  * will replace invalid characters with the underscore (_) character.
  * @param in the input filename.
  * @param replacement the replacement character.
  * @return a valid filename generated by replacing the invalid characters.
  */
public static String generateValidFilename(String in, char replacement) {
   char data[]=in.toCharArray();
   char repChar=replacement; 
   if (isInvalidFileChar(replacement)) 
        repChar='_';
   for (int i=0;i<data.length;i++) 
       if (isInvalidFileChar(data[i])) 
           data[i]=repChar;
   return new String(data);
} // end-method

// --------------------------------------------------------------------------

/** Generates a valid filename from the given filename, 
  * replacing invalid characters with an underscore (_).
  * @param in the input filename.
  * @return a valid filename generated by replacing the invalid characters.
  */
public static String generateValidFilename(String in) {
   return generateValidFilename(in, '_');
} // end-method

// --------------------------------------------------------------------------

/** Tests to see if the specified character is an invalid filename character.
  * @param c the character to test.
  * @return <b>true</b> if the input character is invalid in filenames, <b>false</b> otherwise.
  */
public static boolean isInvalidFileChar(char c) {
   for (int i=0;i<invalidFileCharactersArray.length;i++) {
      if (c==invalidFileCharactersArray[i]) return true;
   } /* endfor */
   return false;
} // end-method
    
}
