Prompt Index PK_CONFIG_SEND_REPORT;
--
-- PK_CONFIG_SEND_REPORT  (Index) 
--
--  Dependencies: 
--   CONFIG_SEND_REPORT (Table)
--
CREATE UNIQUE INDEX PK_CONFIG_SEND_REPORT ON CONFIG_SEND_REPORT
(ID_ACCOUNT,MEMBERS,ID_MASTER_REPORT)
/


