-- 
-- Non Foreign Key Constraints for Table CONFIG_SEND_REPORT
-- 
Prompt Non-Foreign Key Constraints on Table CONFIG_SEND_REPORT;
ALTER TABLE CONFIG_SEND_REPORTADD (
  CONSTRAINT PK_CONFIG_SEND_REPORT
 PRIMARY KEY
 (ID_ACCOUNT,MEMBERS,ID_MASTER_REPORT))
/
