DROP TABLE CONFIG_SEND_REPORT CASCADE CONSTRAINTS;

CREATE TABLE CONFIG_SEND_REPORT
(
  ID_ACCOUNT        NUMBER(10)                  NOT NULL,
  ID_MASTER_REPORT  NUMBER(10)                  NOT NULL,
  MEMBERS           NUMBER(10)                  NOT NULL,
  PERIODICITY       CHAR(1 BYTE)                    NULL,
  NOTIFICATION      VARCHAR2(30 BYTE)               NULL,
  FORMAT            VARCHAR2(30 BYTE)               NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


