Prompt drop TABLE LOGS;
ALTER TABLE LOGS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE LOGS CASCADE CONSTRAINTS PURGE
/

Prompt Table LOGS;
--
-- LOGS  (Table) 
--
CREATE TABLE LOGS
(
  ID           NUMBER(10)                       NOT NULL,
  LOGIN        VARCHAR2(155 BYTE)               NOT NULL,
  PASSWORD     VARCHAR2(155 BYTE)               NOT NULL,
  IP           VARCHAR2(155 BYTE),
  SESSION_ID   VARCHAR2(155 BYTE),
  COMPT        NUMBER(10),
  LAST_VISITE  DATE,
  CONNECTED    VARCHAR2(255 BYTE)
)
/


