Prompt drop TABLE ORGANIZATIONS;
ALTER TABLE ORGANIZATIONS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE ORGANIZATIONS CASCADE CONSTRAINTS PURGE
/

Prompt Table ORGANIZATIONS;
--
-- ORGANIZATIONS  (Table) 
--
CREATE TABLE ORGANIZATIONS
(
  ID             NUMBER(10)                     NOT NULL,
  COD_PAIS       NUMBER(10)                     NOT NULL,
  NAME           VARCHAR2(150 BYTE)             NOT NULL,
  ADDRESS1       VARCHAR2(255 BYTE)             NOT NULL,
  ADDRESS2       VARCHAR2(255 BYTE),
  ZIP_CODE       VARCHAR2(10 BYTE),
  CITY           VARCHAR2(155 BYTE),
  PHONE          VARCHAR2(20 BYTE)              NOT NULL,
  URL            VARCHAR2(255 BYTE),
  EMAIL          VARCHAR2(155 BYTE)             NOT NULL,
  COMMENTS       CLOB,
  CREATED        DATE                           NOT NULL,
  EMAIL_COLLECT  VARCHAR2(155 BYTE)
)
/


