Prompt drop TABLE REPORTS;
ALTER TABLE REPORTS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE REPORTS CASCADE CONSTRAINTS PURGE
/

Prompt Table REPORTS;
--
-- REPORTS  (Table) 
--
CREATE TABLE REPORTS
(
  ID                    NUMBER(10)              NOT NULL,
  OWNER                 NUMBER(10)              NOT NULL,
  NAME                  VARCHAR2(155 BYTE),
  PROJECTS              VARCHAR2(255 BYTE),
  MEMBERS               VARCHAR2(255 BYTE),
  PRIORITIES            VARCHAR2(255 BYTE),
  STATUS                VARCHAR2(255 BYTE),
  START_DATE_START      DATE,
  END_DATE_START        DATE,
  START_DATE_DUE        DATE,
  END_DATE_DUE          DATE,
  IND_RANGE_START_DATE  VARCHAR2(10 BYTE),
  IND_RANGE_DUE_DATE    VARCHAR2(10 BYTE),
  CREATED               DATE                    NOT NULL,
  SPREADFIX             VARCHAR2(3 BYTE),
  IND_RANGE_END_DATE    VARCHAR2(10 BYTE),
  START_DATE_END        DATE,
  END_DATE_END          DATE,
  TYPETASKS             VARCHAR2(255 BYTE)
)
/


