Prompt drop TABLE RISKS;
ALTER TABLE RISKS
 DROP PRIMARY KEY CASCADE
/
DROP TABLE RISKS CASCADE CONSTRAINTS PURGE
/

Prompt Table RISKS;
--
-- RISKS  (Table) 
--
CREATE TABLE RISKS
(
  ID           NUMBER(10)                       NOT NULL,
  DESCRIPTION  VARCHAR2(255 BYTE)               NOT NULL,
  PROBABILITY  NUMBER(10),
  IMPACT       NUMBER(10),
  TODOACTION   CLOB,
  PLANB        VARCHAR2(255 BYTE),
  TASK         NUMBER(10),
  PROJECT      NUMBER(10)
)
/


