ALTER TABLE SCHEDULES
RENAME COLUMN HOUR_NAME TO HOUR_START;


ALTER TABLE SCHEDULES
 ADD (ID_ACCOUNT           NUMBER(10),
      HOUR_END          VARCHAR2(8 BYTE)            NOT NULL,
      REALTIME_HOURS    NUMBER(10)                  NOT NULL,
      REALTIME_MINUTES  NUMBER(10)                  NOT NULL);


update SCHEDULES set id_account =2;


ALTER TABLE SCHEDULES
MODIFY(ID_ACCOUNT NOT NULL);