ALTER TABLE TASKS
 DROP COLUMN COMMENTS;
 
ALTER TABLE TASKS
 DROP COLUMN TOPIC;
 
ALTER TABLE TASKS
 ADD (COMMENTS                CLOB,
      TOPIC                   NUMBER(10),
      ID_ACCOUNT              NUMBER(10));

update TASKS set id_account = 2;

update TASKS set TOPIC = TOPIC_;

update TASKS set COMMENTS = COMMENTS_;
ALTER TABLE TASKS
 DROP COLUMN COMMENTS_;
 
ALTER TABLE TASKS
 DROP COLUMN TOPIC_;
ALTER TABLE TASKS
MODIFY(ID_ACCOUNT NOT NULL);

ALTER TABLE TASKS
MODIFY(TOPIC NOT NULL);

ALTER TABLE TASKS
MODIFY(COMMENTS NOT NULL);

ALTER TABLE TASKS ADD
(
 REPORTED_BY VARCHAR2(25),
 ORIGIN VARCHAR2(25),
 TYPE VARCAHR2(25)
);